Le  ministre de l'Economie et des Finances a profit&eacute; de la 5&egrave;me &eacute;dition des Assises  de l'Association fran&ccedil;aise d'&eacute;pargne et de retraite (AFER) pour r&eacute;affirmer la  volont&eacute; du gouvernement de r&eacute;former l'&eacute;pargne retraite. L'op&eacute;ration s'est av&eacute;r&eacute;e  payante puisque les mesures pr&eacute;sent&eacute;es, aussi ambitieuses les unes que les  autres, ont obtenu l&rsquo;assentiment des membres de l&rsquo;AFER, &agrave; seulement quelques  semaines de la pr&eacute;sentation du projet de loi PACTE au Parlement.
<br>
<br>
Pour  convaincre, le ministre a mis&eacute; sur une offre d&rsquo;&eacute;pargne simplifi&eacute;e. Il a fait  savoir que les &eacute;pargnants auraient la possibilit&eacute; de <strong>regrouper leur &eacute;pargne  au sein d'un seul et m&ecirc;me produit de leur choix</strong>. Chaque produit serait  alors dot&eacute; de 3&nbsp;enveloppes transf&eacute;rables de mani&egrave;re &agrave; ne pas remettre en cause  leurs caract&eacute;ristiques&nbsp;: une enveloppe au titre des versements  obligatoires de l'entreprise, une autre contenant l'int&eacute;ressement et la  participation, enfin, une derni&egrave;re pour les versements volontaires.
<br>
<br>
Souhaitant  promouvoir la libert&eacute; de chacun, il a d&eacute;clar&eacute; vouloir <strong>g&eacute;n&eacute;raliser les  modalit&eacute;s de sortie en capital</strong> pour les versements volontaires et les  sommes issues de l&rsquo;int&eacute;ressement et de la participation. Ce <strong>gage de flexibilit&eacute;</strong> devrait permettre aux Fran&ccedil;ais de mieux reconsid&eacute;rer les produits d&rsquo;&eacute;pargne  retraite, aujourd&rsquo;hui d&eacute;laiss&eacute;s pour l&rsquo;assurance vie. Bien que le pr&eacute;sident de  l&rsquo;association ait salu&eacute; cette initiative, cette mesure, loin de faire  l&rsquo;unanimit&eacute; aupr&egrave;s des professionnels, est vivement <strong>critiqu&eacute;e par les  assureurs</strong>. Selon eux, le gouvernement devrait plut&ocirc;t privil&eacute;gier les  sorties en rente pour faire face &agrave; l&rsquo;allongement de l&rsquo;esp&eacute;rance de vie qui accro&icirc;t,  sur le long terme, les besoins de protection&nbsp;financi&egrave;re des retrait&eacute;s.
<br>
Pourtant,  loin de se d&eacute;sint&eacute;resser du pouvoir d&rsquo;achat des retrait&eacute;s, le gouvernement  entend <strong>harmoniser les motifs de retraits anticip&eacute;s</strong> et permettre,  notamment, aux &eacute;pargnants d&rsquo;investir dans l&rsquo;acquisition de la r&eacute;sidence  principale.
<br>
Du  c&ocirc;t&eacute; de la<strong> taxation</strong>, &eacute;l&eacute;ment non n&eacute;gligeable, le ministre assure qu'il n'y  aurait pas de remise en cause de l&rsquo;avantage fiscal appliqu&eacute; sur les versements  volontaires. Bien au contraire, il met l'accent sur ce r&eacute;gime incitatif en  pr&eacute;cisant que ces versements seraient d&eacute;ductibles des revenus dans la limite  des plafonds existants.
<br>
<br>
Pour  conclure, le discours se voulait rassurant quant aux <strong>perspectives de  rendements des produits</strong>. L&rsquo;option de <strong>gestion pilot&eacute;e</strong> serait g&eacute;n&eacute;ralis&eacute;e  et permettrait de rechercher la performance et de s&eacute;curiser l&rsquo;&eacute;pargne au fur et  &agrave; mesure que la date de la retraite approche. De fait, lorsque cette option serait  coupl&eacute;e &agrave; une allocation investie &agrave; hauteur de 10&nbsp;% minimum en titres de petites  et moyennes entreprises et d&rsquo;entreprises de taille interm&eacute;diaire, l'employeur  b&eacute;n&eacute;ficierait d'une baisse du <strong>forfait social de 20&nbsp;% &agrave; 16&nbsp;%</strong>. Enfin, <strong>changer  de prestataire s'av&eacute;rerait moins co&ucirc;teux </strong>: plus aucun frais ne serait  demand&eacute;<strong> </strong>&agrave; partir d&rsquo;une certaine dur&eacute;e de d&eacute;tention et en cas de  changement d&rsquo;activit&eacute; professionnelle (en dehors de ces cas, les <strong>frais  seraient plafonn&eacute;s</strong>).
<br>
<br>
<strong>Note</strong> : <em>Comme  l&rsquo;avait d&eacute;j&agrave; annonc&eacute; le ministre en mati&egrave;re d&rsquo;assurance vie (voir notre  <a href="../../nlp_2018/newsletter_18_03_30/newsletter_article_1.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent article</a>), les <strong>fonds euros</strong> <strong>ne seraient pas r&eacute;form&eacute;s</strong> par la future loi PACTE<strong> contrairement aux fonds Euro-croissance</strong>, qui eux, verraient leur  fonctionnement modernis&eacute;. Ainsi, il serait envisag&eacute; de mettre en place un &quot;rendement  unifi&eacute; et lisible pour tous les &eacute;pargnants&quot; pour les fonds  Euro-croissance, rendement qui pourrait &ecirc;tre am&eacute;lior&eacute; si l&rsquo;investisseur  s&rsquo;engage &agrave; rester sur ce type de fonds pendant plusieurs ann&eacute;es.</em>
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://www.patritheque.fr/sources/divers/2018_05_03_Discours_BLM_Assises_AFER.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Disc. Ministre de l'Economie et des Finances, 5eme éd. des Assises de l'association française d'épargne et de retraite, 3 mai 2018</a><br>
	</em>
	<br>
	<br>
