L'activit&eacute; civile et financi&egrave;re  des soci&eacute;t&eacute;s holdings les exclut normalement du champ d'application d'un  certain nombre de dispositifs (r&eacute;duction IR-PME, abattement pr&eacute;vu en faveur des  dirigeants partant &agrave; la retraite, pactes Dutreil transmission, exon&eacute;ration des  biens professionnels en mati&egrave;re d'IFI, etc.). Ces diff&eacute;rents <strong>r&eacute;gimes de faveur</strong> ciblent en effet des <strong>soci&eacute;t&eacute;s dites op&eacute;rationnelles</strong>,  c'est-&agrave;-dire des structures ayant une <strong>activit&eacute;  industrielle, commerciale, artisanale, agricole ou lib&eacute;rale</strong>. Les soci&eacute;t&eacute;s  ayant une <strong>activit&eacute; civile</strong>, notamment  les <strong>holdings ayant pour activit&eacute; la</strong> <strong>gestion d'un portefeuille</strong>, sont <strong>en principe</strong> <strong>exclues du champ d'application de ces dispositifs</strong> car elles sont  consid&eacute;r&eacute;es comme &quot;<strong>passives</strong>&quot;.  A c&ocirc;t&eacute; de cela, certaines holdings, dites &quot;<strong>animatrices</strong>&quot;, sont consid&eacute;r&eacute;es comme des soci&eacute;t&eacute;s  op&eacute;rationnelles.
<br>
<br>
L'administration fiscale  consid&egrave;re dans ses commentaires qu'une <strong>holding  animatrice</strong> est une holding qui, outre la gestion d&rsquo;un portefeuille de  participations, <strong>participe activement &agrave;  la conduite de la politique du groupe et au contr&ocirc;le des filiales</strong>, et rend,  le cas &eacute;ch&eacute;ant et &agrave; titre purement interne, des services sp&eacute;cifiques,  administratifs, juridiques, comptables, financiers et immobiliers. Cette  d&eacute;finition suscite cependant de <strong>nombreuses  difficult&eacute;s</strong> lorsqu'il s'agit de la mettre en &oelig;uvre <strong>en pratique</strong>.
<br>
<br>
En t&eacute;moigne un litige opposant  l'administration fiscale &agrave; des contribuables qui, estimant que la soci&eacute;t&eacute;  holding dont ils d&eacute;tenaient les parts &eacute;tait une <strong>soci&eacute;t&eacute; animatrice</strong>, avaient fait valoir l'application du r&eacute;gime de  faveur -ancien- permettant aux dirigeants c&eacute;dant leurs droits sociaux de  b&eacute;n&eacute;ficier d'un abattement d'un tiers par an sur leurs plus-values apr&egrave;s  5&nbsp;ann&eacute;es de d&eacute;tention. L'administration consid&eacute;ra de son c&ocirc;t&eacute; que le fait  que la holding exerce par ailleurs d'<strong>autres  activit&eacute;s</strong>, notamment la <strong>gestion de  titres de participations </strong>(dont la valeur avait consid&eacute;rablement cru tandis  que la valeur v&eacute;nale de la soci&eacute;t&eacute; contr&ocirc;l&eacute;e d&eacute;croissait dans le m&ecirc;me temps&hellip;)  faisait <strong>obstacle &agrave; cette qualification</strong>.
<br>
<br>
Les contribuables ont saisi la  justice afin de demander &agrave; &ecirc;tre d&eacute;charg&eacute;s de la cotisation d'imp&ocirc;t suppl&eacute;mentaire  mise &agrave; leur charge. Le <strong>Conseil d'Etat</strong>,  r&eacute;uni en formation pl&eacute;ni&egrave;re, leur a donn&eacute; raison, et <strong>assouplit</strong>,<strong> </strong>ce faisant,  la <strong>position de l'administration fiscale</strong> eu &eacute;gard aux holdings ayant une activit&eacute; mixte. Les juges ont ainsi consid&eacute;r&eacute;,  &agrave; la lumi&egrave;re des travaux parlementaires relatifs &agrave; l'instauration de cet  abattement, qu'il suffisait que cette activit&eacute; soit l'<strong>activit&eacute; principale de la holding</strong> pour que celle-ci soit consid&eacute;r&eacute;e  comme une <strong>soci&eacute;t&eacute; animatrice</strong>.
<br>
<br>
<strong>Note</strong> : <em>Cette solution devrait  pouvoir &ecirc;tre &eacute;tendue aux autres dispositifs faisant appel &agrave; cette notion, et  notamment en mati&egrave;re d'IFI. Il convient n&eacute;anmoins d'&ecirc;tre prudent en attendant  que celle-ci soit confirm&eacute;e.</em>
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('https://www.legifrance.gouv.fr/affichJuriAdmin.do?oldAction=rechJuriAdmin&idTexte=CETATEXT000037059301','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">CE ass. plén., n° 395495, 13 juin 2018</a><br>
	</em>
	<br>
	<br>

