Elargi et prorog&eacute; jusqu&rsquo;au 31&nbsp;d&eacute;cembre&nbsp;2020 par la loi de finances pour 2018 (voir notre <a href="../../nlp_2018/newsletter_18_01_11/newsletter_article_3.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent  article</a>), les nouveaut&eacute;s relatives au cr&eacute;dit d&rsquo;imp&ocirc;t en faveur de l&rsquo;aide aux personnes  viennent d&rsquo;&ecirc;tre int&eacute;gr&eacute;es dans le BOFiP le 15&nbsp;juin dernier.
<br>
Les commentaires de  l&rsquo;administration &eacute;clairent sur certains points sp&eacute;cifiques, essentiellement  relatifs au nouveau volet du cr&eacute;dit d&rsquo;imp&ocirc;t affectant les <strong>d&eacute;penses d'installation ou de remplacement d'&eacute;quipements permettant  l'adaptation des logements &agrave; la perte d'autonomie ou au handicap r&eacute;alis&eacute;es &agrave;  compter du 1er&nbsp;janvier&nbsp;2018.</strong>
<br>
Au m&ecirc;me titre que le dispositif  d&eacute;j&agrave; en place aff&eacute;rent aux &eacute;quipements sp&eacute;cialement con&ccedil;us pour l'accessibilit&eacute;  aux logements aux personnes &acirc;g&eacute;es ou handicap&eacute;es, ce nouveau volet s&rsquo;applique sans  distinction aux contribuables propri&eacute;taires, locataires ou occupants &agrave; titre  gratuit de leur habitation principale. Toutefois, <strong>dans le cadre de ce nouveau volet, le b&eacute;n&eacute;fice du cr&eacute;dit d&rsquo;imp&ocirc;t est  subordonn&eacute; &agrave; la condition que le contribuable, ou un membre de son foyer  fiscal, soit en situation de perte d&rsquo;autonomie ou de handicap. </strong>
<br>
Plus pr&eacute;cis&eacute;ment, le  contribuable, ou un membre de son foyer fiscal, doit, pour b&eacute;n&eacute;ficier du cr&eacute;dit  d&rsquo;imp&ocirc;t, &ecirc;tre titulaire de la carte mobilit&eacute; inclusion ou d'une carte  handicap&eacute;, ou b&eacute;n&eacute;ficier d'une pension militaire ou de victime de guerre pour  invalidit&eacute; d'au moins 40&nbsp;%, d'une pension d'invalidit&eacute; pour accident du travail  d'au moins 40&nbsp;% ou pouvoir b&eacute;n&eacute;ficier de l'allocation personnalis&eacute;e d'autonomie  (APA).
<br>
<br>
Dans ses commentaires, l&rsquo;administration est venue pr&eacute;ciser  les contours et limites de certaines de ces situations, elle pr&eacute;voit notamment&nbsp;:
    <ul class="ul">
      <li class="puce">que  les titulaires d&rsquo;une <strong>pension militaire  ou de victime de guerre allou&eacute;e &agrave; titre de veuvage</strong> ne remplissent pas la  condition d&rsquo;ouverture au cr&eacute;dit d&rsquo;imp&ocirc;t d&egrave;s lors que la pension ne leur est pas  accord&eacute;e au titre d&rsquo;une invalidit&eacute;&nbsp;;</li>
      <li class="puce">un <strong>temp&eacute;rament</strong> sur la <strong>date d&rsquo;appr&eacute;ciation de la condition de  perte d&rsquo;autonomie ou de handicap</strong>. Ainsi, le cr&eacute;dit d&rsquo;imp&ocirc;t peut s&rsquo;appliquer  si le contribuable justifie, d&rsquo;une part, &agrave; la date d&rsquo;appr&eacute;ciation normale de la  condition (&agrave; savoir, selon les cas, le 31&nbsp;d&eacute;cembre de l'ann&eacute;e du paiement de la  d&eacute;pense, &agrave; la date d&rsquo;acquisition du logement ou &agrave; la date de son ach&egrave;vement),  d&rsquo;un accus&eacute; de r&eacute;ception d&eacute;livr&eacute; par l&rsquo;instance comp&eacute;tente visant &agrave; l&rsquo;obtention  d&rsquo;une carte mobilit&eacute; inclusion ou n&eacute;cessitant un classement dans l&rsquo;un des  groupes 1 &agrave; 4 de la grille AGGIR et, d&rsquo;autre part, de l&rsquo;obtention effective, &agrave;  la suite de cette demande, de la carte ou du classement&nbsp;;</li>
      <li class="puce">une <strong>mesure de tol&eacute;rance sur la notion  d&rsquo;habitation principale</strong>. Par exception, au titre de ce volet perte  d'autonomie et handicap, le cr&eacute;dit d&rsquo;imp&ocirc;t s&rsquo;applique &eacute;galement aux d&eacute;penses  r&eacute;alis&eacute;es &agrave; l&rsquo;ext&eacute;rieur de l&rsquo;habitation principale et de ses d&eacute;pendances  imm&eacute;diates et n&eacute;cessaires si les &eacute;quipements &eacute;ligibles au cr&eacute;dit d&rsquo;imp&ocirc;t sont  install&eacute;s sur leurs seuls chemins d&rsquo;acc&egrave;s. L&rsquo;administration pr&eacute;cise que cette tol&eacute;rance  ne devrait concerner, en pratique, que les d&eacute;penses relatives aux syst&egrave;mes de <strong>motorisation des portails</strong> et aux <strong>rev&ecirc;tements de sol antid&eacute;rapants</strong>.
    </ul>
<br>

<strong>Note&nbsp;:</strong> <em>Ces diff&eacute;rents points seront int&eacute;gr&eacute;s dans votre Patrith&egrave;que disponible &agrave; partir du  27 juin.</em>
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://bofip.impots.gouv.fr/bofip/4734-PGP','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">BOFiP-Impôts, BOI-IR-RICI-290-10, 15 juin 2018</a><br>
	</em>
	<br>
	<br>
