Dans son rapport annuel sur la  situation financi&egrave;re des organismes compl&eacute;mentaires sant&eacute;, la Direction de la  recherche, des &eacute;tudes, de l'&eacute;valuation et des statistiques (DREES) dresse un <strong>bilan mitig&eacute;</strong> de l'impact, en 2016, de  la g&eacute;n&eacute;ralisation de la compl&eacute;mentaire sant&eacute; sur le march&eacute; des contrats  collectifs.
<br>
<br>
Souvenez-vous, cette r&eacute;forme  devait favoriser l'acc&egrave;s aux soins des salari&eacute;s et permettre aux organismes  assureurs (paritaires, mutualistes et assureurs) de souscrire davantage de  contrats collectifs. Sur le 1er&nbsp;point, elle a effectivement permis de <strong>couvrir entre 1,25 et 1,50&nbsp;million de  personnes en plus en 2016</strong> (ceci &eacute;tant, 90&nbsp;% de la population en France  &eacute;tait d&eacute;j&agrave; couverte par une compl&eacute;mentaire sant&eacute; avant la r&eacute;forme). Sur le  2nd&nbsp;point, <strong>la part des contrats  collectifs a bien augment&eacute;</strong> (46&nbsp;% des cotisations collect&eacute;es en 2016 contre  44&nbsp;% en 2015), mais sans transformer significativement le march&eacute;, d'autant plus  que ces contrats gagnaient d&eacute;j&agrave; du terrain sur les contrats individuels, avant  la g&eacute;n&eacute;ralisation obligatoire.
<br>
<br>
<strong>Note</strong> : <em>Par  &quot;paritaires&quot;, la DREES d&eacute;signe les institutions de pr&eacute;voyance  ind&eacute;pendantes et les organismes appartenant &agrave; des groupes de protection sociale  g&eacute;r&eacute;s par des institutions de pr&eacute;voyance. Les &quot;mutualistes&quot;  rassemblent les groupes mutualistes ainsi que les mutuelles ind&eacute;pendantes.  Enfin, les &quot;assureurs&quot; forment les groupes d&rsquo;assurances et les  soci&eacute;t&eacute;s d&rsquo;assurances ind&eacute;pendantes.</em>
<br>
<br>
R&eacute;sultat des courses, les  contrats collectifs ont g&eacute;n&eacute;r&eacute;<strong> plus de  912&nbsp;millions d'euros de cotisations </strong>en 2016, dont la quasi-totalit&eacute; collect&eacute;e  par seulement 9&nbsp;organismes (5&nbsp;assureurs et 4&nbsp;paritaires) sur 492. Bien que les  mutuelles dominent le march&eacute; de l'assurance sant&eacute;, ces chiffres refl&egrave;tent  l'&eacute;volution de ces derni&egrave;res ann&eacute;es : les soci&eacute;t&eacute;s d&rsquo;assurance et institutions  de pr&eacute;voyance ont accru leur activit&eacute; en collectif mais ont perdu de l&rsquo;activit&eacute;  en individuel, alors qu'&agrave; l'inverse, les mutuelles ont peu augment&eacute; leur  activit&eacute; collective, mais ont maintenu leur activit&eacute; en individuel (en raison  de leur pr&eacute;sence dans des secteurs exclus du p&eacute;rim&egrave;tre de la r&eacute;forme, comme la  fonction publique).<br>
Globalement, les organismes assureurs  ont d&eacute;gag&eacute; de <strong>l&eacute;gers exc&eacute;dents  techniques sur leur activit&eacute; sant&eacute;</strong> (104&nbsp;millions d'euros en 2016), soit 0,3&nbsp;% des cotisations collect&eacute;es hors taxes. On ne peut, toutefois, pas attribuer  cette hausse &agrave; la seule r&eacute;forme, puisque cette tendance s'observait d&eacute;j&agrave; depuis  quelques ann&eacute;es. De surcro&icirc;t, elle r&eacute;sulte davantage des contrats individuels,  ces derniers &eacute;tant exc&eacute;dentaires depuis 2014 par rapport aux contrats  collectifs qui eux &eacute;taient d&eacute;ficitaires. Force est de constater que <strong>la rentabilit&eacute; de ces 2&nbsp;types de contrats  ne semble pas avoir &eacute;t&eacute; affect&eacute;e par la g&eacute;n&eacute;ralisation</strong>. <br>
La DREES constate, par ailleurs, que les organismes n'ont pas mobilis&eacute; beaucoup  de leurs ressources pour gagner des parts de march&eacute;s (ceux qui en ont profit&eacute;  &eacute;taient d&eacute;j&agrave; implant&eacute;s) et ont davantage cherch&eacute; &agrave; se mettre en conformit&eacute; avec  &agrave; la nouvelle r&eacute;glementation sur les contrats responsables et leurs obligations  d'information. Malgr&eacute; tout, les <strong>assureurs  ont su tirer profit </strong>de ces &eacute;volutions puisqu'il s'agit de la cat&eacute;gorie  d'organisme dont le chiffre d'affaires sur les contrats collectifs a le plus  augment&eacute; entre 2015 et 2016 (615&nbsp;millions d&rsquo;euros de cotisations collect&eacute;es  suppl&eacute;mentaires sur un total de 912&nbsp;millions).
<br>
<br>
Le secteur assurantiel de la  sant&eacute; reste, sans conteste, un march&eacute; important puisqu'il repr&eacute;sente <strong>15&nbsp;% du chiffre d'affaires des organismes  assureurs</strong>. Pour autant, le nombre d'organismes pratiquant cette activit&eacute; est  en baisse depuis plusieurs ann&eacute;es et la r&eacute;forme n'a rien arrang&eacute; (42&nbsp;organismes  en moins en 2016 alors qu'entre 2011 et 2015 on en perdait seulement 30 &agrave; 40 chaque  ann&eacute;e).
<br>
<br>
	<em><strong>Sources </strong>: <br>
	>&nbsp;<a href="javascript:var w=window.open('http://drees.solidarites-sante.gouv.fr/IMG/pdf/er1064.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">DREES, La généralisation de la complémentaire santé, 24 mai 2018</a><br>
	>&nbsp;<a href="javascript:var w=window.open('http://drees.solidarites-sante.gouv.fr/IMG/pdf/rapport_2017_sur_la_situation_financiere_des_organismes_complementaires_assurant_une_couverture_sante-2.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">DREES, Situation financière des organismes complémentaires assurant une couverture santé, éd. 2017</a><br>
	</em>
	<br>
	<br>
