En attendant la parution, au  BOFiP, le 8&nbsp;juin prochain au plus tard, des commentaires relatifs &agrave; l'imp&ocirc;t sur  la fortune immobili&egrave;re (IFI) (voir notre <a href="../../nlp_2018/newsletter_18_05_23/newsletter_article_1.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent article</a>),  un d&eacute;cret, paru au Journal officiel le 26 mai dernier, apporte des  clarifications attendues sur les <strong>obligations  respectives</strong> des <strong>redevables</strong> et des <strong>soci&eacute;t&eacute;s</strong> et <strong>organismes</strong> quant &agrave; la d&eacute;termination de la <strong>fraction de la valeur </strong>des <strong>parts  et des actions</strong> <strong>de soci&eacute;t&eacute;s ou  d'organismes</strong> <strong>repr&eacute;sentative de  droits immobiliers</strong>.
<br>
<br>
Ce d&eacute;cret pr&eacute;voit que lesdites soci&eacute;t&eacute;s  et organismes <strong>doivent</strong> <strong>communiquer au redevable</strong>,<strong> sur sa demande</strong>, les<strong> &eacute;l&eacute;ments n&eacute;cessaires &agrave; la d&eacute;termination de  cette fraction imposable</strong>. Les <strong>organismes  de placement collectif</strong> (directement ou via leur soci&eacute;t&eacute; de gestion) se  voient imposer la m&ecirc;me obligation, de m&ecirc;me que les <strong>organismes d'assurance et assimil&eacute;s</strong> (les souscripteurs devant  &eacute;galement, pour rappel, d&eacute;clarer -le cas &eacute;ch&eacute;ant- la fraction de la valeur de  rachat des contrats d'assurance et des bons ou contrats de capitalisation  repr&eacute;sentative de biens et de droits immobiliers qu'ils d&eacute;tiennent). Cette  obligation s'applique enfin, dans les m&ecirc;mes termes, aux administrateurs de <strong>trust</strong> et aux <strong>fiduciaires</strong> eu &eacute;gard aux actifs immobiliers plac&eacute;s dans des trusts  ou dans des fiducies.
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000036944234','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Décr. n° 2018-391, 25 mai 2018, JO 26 mai</a><br>
	</em>
	<br>
	<br>
