	Le <strong>cr&eacute;dit d'imp&ocirc;t</strong> accord&eacute; au titre des <strong>d&eacute;penses d'&eacute;quipements  de l'habitation principale</strong> adapt&eacute;s aux <strong>personnes  handicap&eacute;es</strong> ou souffrant d&rsquo;une<strong> perte  d&rsquo;autonomie </strong>a &eacute;t&eacute; prorog&eacute; jusqu'au<strong> 31&nbsp;d&eacute;cembre&nbsp;2020 </strong>par la loi de finances pour 2018 (voir notre <a href="http://www.patritheque.fr/dossiers/lf_2018/lf2018_9.asp#CI_EQUIP" class="lien_intro_souligne">dossier  sp&eacute;cial LF 2018</a>).  
<br />Il a en outre &eacute;t&eacute; <strong>&eacute;tendu</strong>, &agrave; compter  du 1er&nbsp;janvier&nbsp;2018, aux d&eacute;penses d&rsquo;installation ou de  remplacement d&rsquo;&eacute;quipements permettant l&rsquo;<strong>adaptation </strong>des <strong>logements</strong> &agrave; la perte  d&rsquo;autonomie ou au handicap &agrave; condition que le contribuable ou un membre de son  foyer fiscal puisse<strong> </strong>justifier d&rsquo;une telle  situation (b&eacute;n&eacute;ficiaire de l'allocation personnalis&eacute;e d'autonomie, titulaire de  la carte mobilit&eacute; inclusion, etc.). <br>
    <br>
    Un arr&ecirc;t&eacute;, paru au Journal officiel, fixe la liste des<strong> &eacute;quipements &eacute;ligibles</strong> au dispositif  pour les d&eacute;penses r&eacute;alis&eacute;es <strong>&agrave; compter du  1er&nbsp;janvier&nbsp;2018 </strong>(sous r&eacute;serve, comme habituellement,  qu&rsquo;ils soient attach&eacute;s &agrave; perp&eacute;tuelle demeure).
    <br><br>
    Concernant l'<strong>accessibilit&eacute;</strong> des logements aux <strong>personnes &acirc;g&eacute;es</strong> ou <strong>handicap&eacute;es</strong>, la liste des  &eacute;quipements &eacute;ligibles est d&eacute;sormais la suivante&nbsp;:
<ul class="ul"><li class="puce"><strong>&eacute;quipements sanitaires</strong> : les &eacute;viers et les lavabos &agrave; hauteur r&eacute;glable, les siphons d&eacute;port&eacute;s, les si&egrave;ges de douche muraux et les WC sur&eacute;lev&eacute;s ;</li>
    <li class="puce"><strong>&eacute;quipements de s&eacute;curit&eacute; et d'accessibilit&eacute;</strong> : les appareils &eacute;l&eacute;vateurs verticaux comportant une plate-forme am&eacute;nag&eacute;e en vue du transport d'une personne handicap&eacute;e et &eacute;l&eacute;vateurs &agrave; d&eacute;placements inclin&eacute;s sp&eacute;cialement con&ccedil;us pour le d&eacute;placement d'une personne handicap&eacute;e, les mains courantes, les barres de maintien ou d'appui, les poign&eacute;es ou barres de tirage de porte adapt&eacute;es, les rampes fixes, les plans inclin&eacute;s, les mobiliers &agrave; hauteur r&eacute;glable, les rev&ecirc;tements podotactiles et les nez de marche contrast&eacute;s et antid&eacute;rapants.</li></ul><br />
    
    S&rsquo;agissant de l'<strong>adaptation</strong> des logements &agrave; la <strong>perte d'autonomie</strong> ou au <strong>handicap</strong>, sont  &eacute;ligibles&nbsp;:
<ul class="ul"><li class="puce"><strong>&eacute;quipements sanitaires</strong> : les &eacute;viers et les lavabos fixes utilisables par les personnes &agrave; mobilit&eacute; r&eacute;duite, les cabines de douche int&eacute;grales pour personnes &agrave; mobilit&eacute; r&eacute;duite, les bacs &agrave; douche extra-plats et portes de douche, les receveurs de douche &agrave; carreler, les pompes de relevage ou pompes d'aspiration des eaux pour receveur extra-plat, les WC suspendus avec b&acirc;ti support, les WC &eacute;quip&eacute;s d'un syst&egrave;me lavant et s&eacute;chant, les robinetteries pour personnes &agrave; mobilit&eacute; r&eacute;duite, les mitigeurs thermostatiques et les miroirs inclinables pour personnes &agrave; mobilit&eacute; r&eacute;duite ;</li>
    <li class="puce"><strong>&eacute;quipements de s&eacute;curit&eacute; et d'accessibilit&eacute;</strong> : les syst&egrave;mes de commande comprenant un d&eacute;tecteur de mouvements, de signalisation ou d'alerte, les dispositifs de fermeture, d'ouverture ou syst&egrave;mes de commande des installations &eacute;lectriques, d'eau, de gaz et de chauffage, les &eacute;clairages temporis&eacute;s coupl&eacute;s &agrave; un d&eacute;tecteur de mouvements, les syst&egrave;mes de motorisation de volets, de portes d'entr&eacute;e et de garage, de portails, les volets roulants &eacute;lectriques, les rev&ecirc;tements de sol antid&eacute;rapant, les protections d'angles, les boucles magn&eacute;tiques, les syst&egrave;mes de transfert &agrave; demeure ou potences au plafond, les garde-corps, les portes ou fen&ecirc;tres adapt&eacute;es, l'inversion ou l'&eacute;largissement de portes et enfin les portes coulissantes.</li></ul><br /><br />
    <strong>Note</strong> : <em>Les am&eacute;nagements  apport&eacute;s &agrave; ce dispositif seront d&eacute;taill&eacute;s dans votre Patrith&egrave;que &agrave; para&icirc;tre fin  janvier.</em><br><br>
	<br />

	<!-- En prèsence d"une seule source, supprimer la "puce" et remonter le texte sur la même ligne que "Sources :" -->
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000036342675','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Arr. 30 d&eacute;c. 2017, JO 31 d&eacute;c.</a><br></em>
<br>
	<br>


