Une <strong>demi-part suppl&eacute;mentaire</strong> est accord&eacute;e aux personnes <strong>veuves</strong> ayant &eacute;lev&eacute; seules un enfant pendant <strong>5&nbsp;ans</strong>. L'administration vient de  pr&eacute;ciser que ce d&eacute;lai devait &ecirc;tre d&eacute;compt&eacute; uniquement<strong> &agrave; compter de l'ann&eacute;e civile suivant celle du d&eacute;c&egrave;s du conjoint</strong>.
<br>
Le point de d&eacute;part de ce d&eacute;lai  n'avait jusqu'alors encore jamais &eacute;t&eacute; pr&eacute;cis&eacute;. En effet, le texte de loi  indique uniquement que la demi-part suppl&eacute;mentaire b&eacute;n&eacute;ficie aux contribuables  qui vivent &quot;seuls et ont un ou plusieurs enfants majeurs ou faisant  l'objet d'une imposition distincte dont ces contribuables ont support&eacute; &agrave; titre  exclusif ou principal la charge pendant au moins 5&nbsp;ann&eacute;es au cours desquelles  ils vivaient seuls&quot;. La jurisprudence et la doctrine n'ont pas non plus  approfondi le sujet.
<br>
C'est la raison pour laquelle la  question du point de d&eacute;part de la p&eacute;riode de 5&nbsp;ans a &eacute;t&eacute; r&eacute;cemment soumise au <strong>minist&egrave;re de l'Economie et des Finances, </strong>qui a r&eacute;pondu qu'il fallait attendre <strong>l'ann&eacute;e civile suivant l'ann&eacute;e du d&eacute;c&egrave;s du conjoint du contribuable</strong>, et non commencer le d&eacute;compte d&egrave;s la date du d&eacute;c&egrave;s. L'administration justifie cette r&eacute;ponse en pr&eacute;cisant que l'ann&eacute;e du d&eacute;c&egrave;s le  conjoint survivant est impos&eacute; en tenant compte de sa situation de personne  mari&eacute;e ou pacs&eacute;e au 1er&nbsp;janvier et <strong>conserve toutes les majorations de quotient familial</strong> retenues pour  l'imposition commune, y compris sur la p&eacute;riode post&eacute;rieure au d&eacute;c&egrave;s. C'est  pourquoi le d&eacute;compte de la p&eacute;riode de 5&nbsp;ans ne peut d&eacute;buter que le 1er&nbsp;janvier de l'ann&eacute;e suivant celle du d&eacute;c&egrave;s du conjoint.
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://www.senat.fr/questions/base/2017/qSEQ170700257.html','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Rép. min. à M. Malhuret, n° 00257, JOANQ 22 févr. 2018</a><br>
	</em>
	<br>
	<br>
