Le texte de la directive sur la  distribution d'assurances (dite &quot;directive DDA&quot;), adopt&eacute; le 20&nbsp;janvier&nbsp;2016, a vocation &agrave; <strong>r&eacute;organiser  les pratiques de commercialisation des produits d'assurance et de r&eacute;assurance</strong> dans les Etats membres de l'Union europ&eacute;enne. Sont concern&eacute;s par ce texte,  aussi bien les produits d'assurance vie, que ceux d'assurance non-vie qui  regroupent notamment l'ensemble des contrats de type IARD (Incendie, Accidents  et Risques Divers). Devant initialement &ecirc;tre transpos&eacute; en droit interne au plus  tard le 23&nbsp;f&eacute;vrier&nbsp;2018, les institutions europ&eacute;ennes, face &agrave; la mobilisation  importante des organismes professionnels, ont finalement d&eacute;cid&eacute; de <strong>reporter l'entr&eacute;e en application</strong> de ce  texte.
<br>
Ainsi, le Parlement europ&eacute;en et  le Conseil de l'UE ont vot&eacute;, respectivement les 1er et 9&nbsp;mars&nbsp;2018,  une <strong>directive modificative</strong> qui  pr&eacute;voit un report de la date limite de transposition mais aussi de la date  d'entr&eacute;e en application de la directive DDA. Les Etats membres de l'UE auront  donc jusqu'au <strong>1er&nbsp;juillet&nbsp;2018 </strong>(et non plus au 23&nbsp;f&eacute;vrier&nbsp;2018) pour pr&eacute;voir les nouvelles r&egrave;gles dans  leurs l&eacute;gislations et r&eacute;glementations nationales, r&egrave;gles qui devront entrer en  vigueur <strong>au plus tard le 1er&nbsp;octobre&nbsp;2018</strong>.
<br>
<br>
L'importance de garantir aux  consommateurs un <strong>niveau de protection  identique</strong> lors de toute op&eacute;ration d'investissement et ce, peu importe le  canal de distribution, reste l'objectif principal recherch&eacute; par le l&eacute;gislateur  europ&eacute;en. Outre une nouvelle exigence de formation continue des assureurs et  des interm&eacute;diaires d'assurance (agents g&eacute;n&eacute;raux, courtiers, etc.), le texte de  la directive vient <strong>uniformiser  l'information pr&eacute;contractuelle</strong> que ces acteurs devront fournir &agrave; leurs  clients avant toute souscription, l'id&eacute;e &eacute;tant notamment de pouvoir comparer  facilement les produits d'assurance. En pratique, les assureurs devront  pr&eacute;parer <strong>2 types de documents  d'information produit</strong> &agrave; remettre &agrave; leurs interm&eacute;diaires pour que ces  derniers puissent commercialiser leurs produits :
    <ul class="ul">
      <li class="puce">l'&quot;IPID&quot;  (pour &quot;Insurance Product Information Document&quot;) qui correspond au  nouveau document de r&eacute;f&eacute;rence pour les produits d'assurance non-vie, document d&eacute;fini  par la pr&eacute;sente directive DDA,</li>
      <li class="puce">le  &quot;KID&quot; (pour &quot;Key Information Document&quot; ou, en fran&ccedil;ais, Document  d'informations cl&eacute;s (DIC)), qui est r&eacute;serv&eacute; aux produits d'investissement  fond&eacute;s sur l'assurance tels que les contrats d'assurance vie en unit&eacute;s de  compte. Cette obligation a d&eacute;j&agrave; &eacute;t&eacute; pr&eacute;vue par le r&egrave;glement &quot;PRIIPs&quot;  qui est entr&eacute; en vigueur le 1er&nbsp;janvier&nbsp;2018 - voir notre pr&eacute;c&eacute;dent <a href="../../nlp_2017/newsletter_17_05_03/newsletter_article_4.asp" class="lien_intro_souligne">article</a>).
    </ul>
<br>


De plus, la directive DDA pr&eacute;voit  des nouvelles obligations en termes de <strong>surveillance  et de gouvernance des produits d'assurance</strong>. Tout nouveau produit  d'assurance con&ccedil;u puis distribu&eacute; devra, dans tous les cas, &ecirc;tre conforme &agrave;  l'int&eacute;r&ecirc;t et aux besoins des clients. Des proc&eacute;dures internes pr&eacute;alables &agrave; son  lancement devront donc &ecirc;tre mises en place pour s'assurer de sa conformit&eacute;. Les  interm&eacute;diaires se verront &eacute;galement appliquer de nouvelles obligations de  reporting vers les assureurs.
<br>
Enfin, dans un souci de <strong>pr&eacute;vention des conflits d'int&eacute;r&ecirc;ts</strong>, les  clients devront recevoir, &agrave; l'avance, des informations claires sur le <strong>statut des personnes</strong> qui vendent des  produits d'assurance et <strong>sur la nature de  leur r&eacute;mun&eacute;ration</strong> (honoraires, commissions ou tout autre type de  r&eacute;mun&eacute;ration ou avantage). Dans tous les cas, les distributeurs ne devront pas  &ecirc;tre r&eacute;mun&eacute;r&eacute;s d'une fa&ccedil;on qui les encourage &agrave; proposer un produit plut&ocirc;t qu'un  autre au client.
<br>
<br>
<strong>Note</strong> : <em>Un projet d'ordonnance  de transposition en droit fran&ccedil;ais serait d&eacute;j&agrave; pr&ecirc;t mais non encore publi&eacute; au  Journal officiel &agrave; ce jour. Des informations sur la directive DDA seront  d&eacute;taill&eacute;es dans votre prochaine version de la Patrith&egrave;que (disponible courant  du mois d'avril).</em>
<br>
<br>
	<em><strong>Sources </strong>: <br>
	>&nbsp;<a href="javascript:var w=window.open('http://www.consilium.europa.eu/fr/press/press-releases/2018/03/09/insurance-distribution-council-delays-application-of-new-rules/pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Comm. presse 112/18, Conseil de l'UE, 9 mars 2018</a><br>
	>&nbsp;<a href="javascript:var w=window.open('http://data.consilium.europa.eu/doc/document/PE-1-2018-INIT/en/pdf ','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Directive 2018 reportant la mise en œuvre de la directive (UE) 2016/97, 2 mars 2018</a><br>
	>&nbsp;<a href="javascript:var w=window.open('http://eur-lex.europa.eu/legal-content/FR/TXT/PDF/?uri=CELEX:32016L0097&from=en','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Directive (UE) 2016/97, 20 janv. 2016, JOUE 2 févr.</a><br>
	</em>
	<br>
	<br>
