	L'Autorit&eacute; des march&eacute;s financiers  (AMF) a organis&eacute; au cours du mois d'octobre 2017 une &eacute;tude des attitudes et  opinions d'&eacute;pargnants &agrave; l'&eacute;gard des produits financiers. Le r&eacute;sultat de cette  enqu&ecirc;te, men&eacute;e sur un &eacute;chantillon repr&eacute;sentatif de la population et qui a &eacute;t&eacute;  publi&eacute;e le 7 f&eacute;vrier dernier, montre une constance quant &agrave; l'attachement des  Fran&ccedil;ais pour les <strong>placements garantis</strong>.  Pour placer une somme importante, les produits s&eacute;curitaires du type livrets  d'&eacute;pargne et comptes sur livret restent toujours privil&eacute;gi&eacute;s (41&nbsp;% des  &eacute;pargnants) avant les contrats d'assurance vie en euros (28&nbsp;%) et  l'&eacute;pargne logement (26&nbsp;%) pour des raisons habituelles de disponibilit&eacute; et  de s&eacute;curit&eacute; de l'&eacute;pargne. <br>
	<br>
	Toutefois, une nouvelle tendance  se profile puisqu'il semblerait qu'une proportion importante des &eacute;pargnants verrait  les actions comme un <strong>outil int&eacute;ressant de  diversification</strong> (56&nbsp;%) et de <strong>d&eacute;veloppement  d'une &eacute;pargne &agrave; long terme </strong>(48&nbsp;%). Bien que cette app&eacute;tence pour la  Bourse ne soit r&eacute;serv&eacute;e qu'&agrave; un nombre encore limit&eacute; de personnes (28&nbsp;%),  cette &eacute;volution laisse penser qu'il existe un <strong>potentiel non n&eacute;gligeable de souscription en actions &agrave; court terme </strong>(autour  de 7&nbsp;% des Fran&ccedil;ais). D'une mani&egrave;re g&eacute;n&eacute;rale, les actions gardent cette  image d'un placement trop risqu&eacute; et r&eacute;serv&eacute; &agrave; des personnes qui s'y  connaissent.<br> 
    Malgr&eacute; le d&eacute;veloppement de  nouvelles habitudes de consommation avec les banques en ligne par exemple, le  conseiller bancaire habituel reste le <strong>principal  prescripteur</strong> dans les choix de souscription (57&nbsp;%). Les conseils de  l'entourage (parents, amis, proches, etc.) peuvent &eacute;galement influencer de  fa&ccedil;on importante la prise de d&eacute;cision lors de la souscription d'un contrat.<br>
    <br>
    Les principales <strong>pr&eacute;occupations</strong> des Fran&ccedil;ais du point de  vue de leur &eacute;pargne restent le financement de <strong>d&eacute;penses impr&eacute;vues</strong> (82&nbsp;%), la constitution d'un<strong> capital en vue de la retraite</strong> (69 %) mais  aussi le financement des<strong> besoins li&eacute;s au  vieillissement</strong> tels que la perte d'autonomie (73&nbsp;%) et les d&eacute;penses de  sant&eacute; (77&nbsp;%). Ces derniers chiffres peuvent d'ailleurs atteindre des  proportions plus &eacute;lev&eacute;es dans le cas o&ugrave; le patrimoine financier d&eacute;tenu d&eacute;passe  les 50&nbsp;000&nbsp;&euro; et plus. Dans tous les cas, le comportement d'&eacute;pargne  reste limit&eacute; en raison principalement d'un <strong>manque  de moyen</strong>. Sur les 27&nbsp;% n'ayant pas pu &eacute;pargner au cours des 12  derniers mois, 80&nbsp;% d'entre eux ont avanc&eacute; cette explication. En moyenne,  l'enqu&ecirc;te indique qu'environ 287&nbsp;&euro; sont mis de c&ocirc;t&eacute; chaque mois de fa&ccedil;on  r&eacute;guli&egrave;re.<br> 
Enfin, s'agissant de la <strong>pr&eacute;paration de la retraite</strong>, seuls  16&nbsp;% des Fran&ccedil;ais proc&egrave;dent &agrave; des virements r&eacute;guliers pour r&eacute;pondre &agrave;  cette pr&eacute;occupation et pr&egrave;s de la moiti&eacute; des &eacute;pargnants n'ont jamais ou  quasiment jamais fait cette d&eacute;marche. Plus inqui&eacute;tant, 54&nbsp;% des &eacute;pargnants  estiment que le montant consacr&eacute; &agrave; leur retraite ne sera pas suffisant.  L'investissement dans les actions pourrait peut-&ecirc;tre &agrave; l'avenir r&eacute;pondre &agrave;  cette probl&eacute;matique.<br />
	<br />

	<!-- En prèsence d"une seule source, supprimer la "puce" et remonter le texte sur la même ligne que "Sources :" -->
	<em><strong>Sources </strong>: <br>
	>&nbsp;<a href="javascript:var w=window.open('http://www.amf-france.org/Actualites/Communiques-de-presse/AMF/annee-2018?docId=workspace%3A%2F%2FSpacesStore%2F0edead31-fc52-4937-a80d-7b17b16200cd','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Comm. presse AMF, 7 f&eacute;vr.  2018</a><br>
	>&nbsp;<a href="javascript:var w=window.open('http://www.patritheque.fr/sources/rapports/2017_12_31_barometre_epargne_AMF.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Barom&egrave;tre de l'&eacute;pargne et de l'investissement, AMF,  d&eacute;c. 2017</a><br>	</em>
<br>
	<br>


