	Les <strong>salari&eacute;s </strong>et <strong>mandataires  sociaux</strong> d&eacute;tenant des <strong>parts</strong> ou <strong>actions</strong> dans une soci&eacute;t&eacute; dans laquelle  ils exer&ccedil;aient leur <strong>fonction principale</strong> pouvaient, sous r&eacute;serve du respect d'un certain nombre de conditions, b&eacute;n&eacute;ficier  d'une <strong>exon&eacute;ration partielle d'ISF</strong> (&agrave;  hauteur de 75&nbsp;% de leur valeur). Le b&eacute;n&eacute;fice de cette exon&eacute;ration &eacute;tait &eacute;galement  susceptible de s'appliquer aux redevables ayant cess&eacute; leurs fonctions pour  faire valoir leur droit &agrave; la <strong>retraite</strong>,  d&egrave;s lors qu'ils d&eacute;tenaient ces <strong>titres</strong> <strong>depuis</strong> <strong>au moins 3&nbsp;ans au moment de la cessation de leurs fonctions</strong>. <br>
    <br>
    La loi pr&eacute;voyait que le b&eacute;n&eacute;fice  de ce r&eacute;gime de faveur &eacute;tait subordonn&eacute;, entre autres, &agrave; la condition que le  contribuable <strong>conserve les titres</strong> pendant une dur&eacute;e d'<strong>au moins 6&nbsp;ans</strong>,  courant &quot;<em>&agrave; compter du <strong>1er&nbsp;fait g&eacute;n&eacute;rateur</strong> au  titre duquel l'<strong>exon&eacute;ration</strong> a &eacute;t&eacute; <strong>demand&eacute;e</strong></em>&quot;. Fallait-il en  conclure, dans l'hypoth&egrave;se, fr&eacute;quente en pratique, o&ugrave; le contribuable b&eacute;n&eacute;ficiait  d&eacute;j&agrave; d'une exon&eacute;ration au titre d'un autre r&eacute;gime de faveur, que ce d&eacute;lai  devait &ecirc;tre pris en compte pour appr&eacute;cier le respect de cette condition ?<br>
    <br>
    C'est la question qui a &eacute;t&eacute; pos&eacute;  &agrave; la Cour de cassation dans le cadre d'un litige opposant l'administration  fiscale &agrave; un dirigeant qui, partant &agrave; la retraite, et ne pouvant plus de ce  fait b&eacute;n&eacute;ficier d'une <strong>exon&eacute;ration totale  d'ISF</strong> en application du r&eacute;gime des <strong>biens  professionnels</strong>, pla&ccedil;a ses titres sous ce r&eacute;gime d'<strong>exon&eacute;ration partielle</strong>, avant de les <strong>c&eacute;der</strong>, l'<strong>ann&eacute;e suivante</strong>.<br>
    <br>
    L'administration fiscale lui  adressa une <strong>proposition de rectification  d'imp&ocirc;t</strong> au motif qu'il n'avait pas <strong>respect&eacute;</strong> la condition de <strong>dur&eacute;e minimale de  conservation</strong> exig&eacute;e pour b&eacute;n&eacute;ficier du r&eacute;gime d'exon&eacute;ration partielle. Pour  se d&eacute;fendre, le contribuable fit valoir qu'au jour de la cession, ses titres &eacute;taient  exon&eacute;r&eacute;s <strong>depuis plus de 6&nbsp;ans </strong>compte  tenu de l'application, avant son d&eacute;part en retraite, du r&eacute;gime d'exon&eacute;ration  pr&eacute;vu en faveur des <strong>biens professionnels</strong>.<br>
    <br>
    Cet argument n'a pas convaincu les  juges. Ils ont consid&eacute;r&eacute; que le <strong>point de  d&eacute;part</strong> du d&eacute;lai de conservation est le jour &agrave; partir duquel le contribuable  commence &agrave; <strong>b&eacute;n&eacute;ficier dudit dispositif</strong>.  Le fait que les actions &eacute;taient exon&eacute;r&eacute;es &agrave; un autre titre avant cette date ne  peut &ecirc;tre retenu pour l'appr&eacute;ciation du respect de la condition de conservation,  laquelle reste propre &agrave; l'octroi de cet avantage. <br>
    <br>
<strong>Note</strong> : <em>Bien que l'<a href="http://www.patritheque.fr/dossiers/lf_2018/lf2018_6.asp" class="lien_intro_souligne">ISF ait  &eacute;t&eacute; remplac&eacute; par l'IFI &agrave; compter de 2018</a>, les  redevables de l'ISF sont, pour rappel, dans l'obligation de respecter les  engagements pris au titre de cet imp&ocirc;t jusqu'&agrave; leur terme, et donc, s'agissant  de ceux ayant b&eacute;n&eacute;fici&eacute; d'une exon&eacute;ration partielle d'ISF au titre des parts et  actions de soci&eacute;t&eacute; dans laquelle ils exer&ccedil;aient leurs fonctions,  obligatoirement conserver leurs titres pour une dur&eacute;e au moins &eacute;gale &agrave; 6 ans  sous peine de remise en cause de l'avantage obtenu.</em>
    <br>	
    <br>
  

<!-- En prèsence d"une seule source, supprimer la "puce" et remonter le texte sur la même ligne que "Sources :" -->
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('https://www.legifrance.gouv.fr/affichJuriJudi.do?oldAction=rechJuriJudi&idTexte=JURITEXT000036648797','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Cass. Com., 14 f&eacute;vr. 2018, n&deg; 16-21119</a></em>
<br>
	<br>


