<strong>Les plus-values  r&eacute;alis&eacute;es depuis le 14&nbsp;novembre&nbsp;2012</strong>, dans  le cadre d&rsquo;un apport de titres &agrave; une soci&eacute;t&eacute; contr&ocirc;l&eacute;e par l&rsquo;apporteur  b&eacute;n&eacute;ficient, sous certaines conditions, d&rsquo;un <strong>report automatique d&rsquo;imposition.</strong> <br>
Avant la mise en place de ce dispositif, diff&eacute;rents r&eacute;gimes  de report d&rsquo;imposition des plus-values r&eacute;alis&eacute;es lors d&rsquo;apports de titres se  sont succ&eacute;d&eacute;s, respectivement applicables jusqu&rsquo;au 1er&nbsp;janvier&nbsp;2000, au 1er&nbsp;janvier&nbsp;2006 et au 1er&nbsp;janvier&nbsp;2014. <br>
Dans le cadre de l&rsquo;articulation de ces r&eacute;gimes, l&rsquo;administration  pr&eacute;voyait que le report constat&eacute; au titre d&rsquo;un des dispositifs ant&eacute;rieurs ne  pouvait se combiner avec le dispositif de report actuellement en vigueur.  Autrement dit, lorsqu&rsquo;une plus-value avait &eacute;t&eacute; plac&eacute;e en report &agrave; raison d&rsquo;un  apport de titres entrant dans le cadre d&rsquo;un dispositif ant&eacute;rieur, et qu&rsquo;un  nouvel apport portant sur ces titres &eacute;tait r&eacute;alis&eacute;, avant&nbsp;2018, g&eacute;n&eacute;rant une  plus-value b&eacute;n&eacute;ficiant elle aussi d&rsquo;un report d&rsquo;imposition mais au titre du  dispositif actuel, l&rsquo;administration consid&eacute;rait que ce second report  d&rsquo;imposition entra&icirc;nait n&eacute;cessairement l&rsquo;expiration du report constat&eacute;  ant&eacute;rieurement. <br>
Le Conseil d&rsquo;Etat, confront&eacute; &agrave; une affaire dans laquelle  &eacute;tait en cause l&rsquo;apport de titres d&eacute;j&agrave; grev&eacute;s d&rsquo;une plus-value en report &agrave;  raison du <strong>dispositif applicable jusqu&rsquo;au  1er&nbsp;janvier&nbsp;2000</strong>, a jug&eacute; que les commentaires de  l&rsquo;administration excluant la possibilit&eacute; du maintien du report en cas de nouvel  apport &eacute;taient contraires &agrave; la loi. <br>
Les juges ont en cons&eacute;quence annul&eacute; partiellement les commentaires  litigieux (pour ce qui concerne le dispositif de report avant&nbsp;2000) et pr&eacute;cis&eacute;  qu&rsquo;un <strong>apport</strong>, <strong>r&eacute;alis&eacute; avant le 1er&nbsp;janvier&nbsp;2018</strong>, de titres d&eacute;j&agrave; grev&eacute;s  d&rsquo;une plus-value en report &agrave; raison du dispositif applicable jusqu&rsquo;en 2000,  pouvait b&eacute;n&eacute;ficier du maintien du report de la plus-value constat&eacute;  ant&eacute;rieurement, &agrave; condition&nbsp;: </p>
<ul class="ul">
  <li class="puce">que la nouvelle op&eacute;ration d&rsquo;apport  respecte les <strong>conditions d&rsquo;application de  l&rsquo;ancien dispositif</strong> (celui en vigueur jusqu&rsquo;en 2000) ;</li>
  <li class="puce">et que la plus-value r&eacute;alis&eacute;e dans le  cadre de ce nouvel apport soit elle-m&ecirc;me <strong>plac&eacute;e  en report au titre du dispositif actuel</strong>, dans sa version en vigueur avant  le 1er&nbsp;janvier&nbsp;2018.
</ul>
<br>
<strong>Note&nbsp;:</strong> <em>Cette solution n&rsquo;est pas  applicable dans le cadre d&rsquo;un apport de titres d&eacute;j&agrave; grev&eacute;s d&rsquo;une plus-value en  report &agrave; raison d&rsquo;un des autres r&eacute;gimes ant&eacute;rieurs vis&eacute;s par les commentaires  de l&rsquo;administration.</em> <br>
<br>
Il convient de pr&eacute;ciser que le dispositif en vigueur depuis  2012 a &eacute;t&eacute; r&eacute;cemment modifi&eacute; par la loi de finances pour 2018. Dor&eacute;navant, le <strong>maintien du report</strong> s&rsquo;applique <strong>de plein droit</strong> aux apports de titres,  r&eacute;alis&eacute;s <strong>depuis le 1er&nbsp;janvier&nbsp;2018</strong>, d&eacute;j&agrave; grev&eacute;s d&rsquo;une plus-value en report &agrave; raison des  dispositifs ant&eacute;rieurs, <strong>d&egrave;s lors que  l&rsquo;apport effectu&eacute; entre dans le champ d&rsquo;application du dispositif actuel. </strong>La  question tranch&eacute;e par le Conseil d'Etat concerne donc uniquement les apports  effectu&eacute;s avant 2018. <br>
<br>
<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://arianeinternet.conseil-etat.fr/arianeinternet/getdoc.asp?id=213528&fonds=DCE&item=1','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">CE, n&deg; 404689, 25 juin 2018</a></em>
	<br>
	<br>

