L'administration fiscale vient de  publier, le 15&nbsp;mai dernier, ses commentaires sur les modalit&eacute;s de mise en &oelig;uvre  du pr&eacute;l&egrave;vement &agrave; la source de l'IR  (PAS), applicable &agrave; compter du 1er&nbsp;janvier&nbsp;2019.&nbsp; <br>
Elle avait d&eacute;j&agrave;, en janvier  dernier, int&eacute;gr&eacute; &agrave; sa doctrine, quelques pr&eacute;cisions concernant les obligations  des collecteurs de la retenue &agrave; la source. Cette fois, elle pr&eacute;cise les  modalit&eacute;s de calcul du PAS int&eacute;ressant directement les contribuables <strong>sans toutefois commenter les mesures  sp&eacute;cifiques &agrave; l'ann&eacute;e blanche</strong>, notamment le cr&eacute;dit d'imp&ocirc;t de modernisation  du recouvrement de l'IR (<strong>CIMR</strong> destin&eacute; &agrave; neutraliser l'IR sur les revenus per&ccedil;us en 2018), les dispositions  relatives aux <strong>revenus exceptionnels</strong> dont l'imposition ne sera pas neutralis&eacute;e au titre de 2018, les<strong> r&egrave;gles anti-abus</strong> pr&eacute;vues en mati&egrave;re de  revenus fonciers (r&egrave;gles d&eacute;rogatoires de d&eacute;duction des travaux pilotables), de d&eacute;duction  au titre de l'&eacute;pargne retraite et des revenus non salari&eacute;s. Ces dispositifs  sp&eacute;cifiques feront l'objet de <strong>commentaires  ult&eacute;rieurs</strong>.
<br>
<br>
La mise &agrave; jour publi&eacute;e par  l'administration fiscale d&eacute;taille&nbsp;:
<ul class="ul">
      <li class="puce">le <strong>champ d'application</strong> du dispositif  (liste des revenus soumis &agrave; la <strong>retenue &agrave;  la source</strong> -1&egrave;re modalit&eacute; de pr&eacute;l&egrave;vement du PAS-, de ceux soumis  &agrave; un <strong>acompte</strong> -2nde&nbsp;modalit&eacute; de pr&eacute;l&egrave;vement du PAS- et des <strong>revenus  exclus du PAS</strong>), </li>
      <li class="puce">le <strong>calcul du pr&eacute;l&egrave;vement</strong> (d&eacute;finition de  l'assiette de la retenue &agrave; la source et de l'acompte pour chaque cat&eacute;gorie de  revenus, d&eacute;termination du taux et facult&eacute; de modulation en cas de changement de  situation),</li>
      <li class="puce">les <strong>modalit&eacute;s pratiques</strong> d'application de  l'<strong>acompte </strong>(les modalit&eacute;s de  pr&eacute;l&egrave;vement de la retenue, int&eacute;ressant surtout les collecteurs, ont d&eacute;j&agrave; &eacute;t&eacute;  pr&eacute;cis&eacute;es en janvier dernier),</li>
      <li class="puce">le  pr&eacute;l&egrave;vement &agrave; la source des <strong>contributions  et pr&eacute;l&egrave;vements sociaux</strong>.
</ul>
<br>

Ce faisant, l'administration a  apport&eacute; quelques pr&eacute;cisions nouvelles, essentiellement des mesures de  simplification d'ordre pratique. <br>
<br>
C'est ainsi qu'elle a pr&eacute;cis&eacute; les  modalit&eacute;s d'application de la retenue &agrave; la source sur les <strong>indemnit&eacute;s journali&egrave;res</strong> par l'employeur en cas de subrogation  (c'est-&agrave;-dire lorsque l'employeur verse lui-m&ecirc;me les indemnit&eacute;s journali&egrave;res  pour le compte des organismes de S&eacute;curit&eacute; sociale). L'employeur n'&eacute;tant pas en  mesure de savoir si ces indemnit&eacute;s sont exon&eacute;r&eacute;es (au titre d'affections de  longues dur&eacute;es), l'administration pr&eacute;cise que seules les indemnit&eacute;s vers&eacute;es au  titre des 60&nbsp;premiers jours doivent &ecirc;tre soumises au PAS et que les indemnit&eacute;s  suivantes n'ont pas &agrave; l'&ecirc;tre. Elle a &eacute;galement pr&eacute;vue des mesures de tol&eacute;rance  pour les primes d'impatriation et d'expatriation.<br>
Les <strong>apprentis</strong> et <strong>stagiaires</strong> b&eacute;n&eacute;ficieront imm&eacute;diatement de l'exon&eacute;ration partielle de leurs revenus  (l'employeur ne pr&eacute;l&egrave;vera la retenue qu'une fois le plafond d'exon&eacute;ration, fix&eacute;  &agrave; 1&nbsp;SMIC annuel brut,  d&eacute;pass&eacute;), pas les <strong>&eacute;tudiants de 25&nbsp;ans au plus</strong> dont les  r&eacute;mun&eacute;rations seront impos&eacute;es d&egrave;s le 1er&nbsp;euro, et qui ne  b&eacute;n&eacute;ficieront de l'abattement (3&nbsp;SMIC mensuels) qu'au moment de la  r&eacute;gularisation de leur IR (au vu de la d&eacute;claration n&deg;&nbsp;2042). <br>
<br>
L'administration fiscale pr&eacute;cise  &eacute;galement les <strong>modalit&eacute;s pratiques de  demande de modulation</strong> du taux du PAS en cas de changement dans sa situation  personnelle (mariage, naissance&hellip;). La loi pr&eacute;voit que le contribuable dispose  de 60&nbsp;jours &agrave; compter de l'&eacute;v&egrave;nement pour le d&eacute;clarer &agrave; l'administration fiscale et ainsi d'obtenir une modulation du taux du PAS. Dans la situation o&ugrave; 2&nbsp;&eacute;v&egrave;nements interviennent dans un d&eacute;lai de 60&nbsp;jours (par exemple mariage et  naissance), l'administration fiscale admet que le contribuable puisse d&eacute;clarer  simultan&eacute;ment ces 2&nbsp;&eacute;v&egrave;nements et que, dans ce cas, le d&eacute;lai de d&eacute;claration  expire dans les 60&nbsp;jours suivant le 2nd&nbsp;&eacute;v&egrave;nement.
<br>
<br>
<strong>Note</strong> : <em>Vous retrouverez  l'ensemble des pr&eacute;cisions apport&eacute;es par l'administration dans la prochaine mise  &agrave; jour de votre Patrith&egrave;que (juin)</em>.
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://bofip.impots.gouv.fr/bofip/11377-PGP','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">BOFiP-Impôts, BOI-IR-PAS, 15 mai 2018</a><br>
	</em>
	<br>
	<br>
