Cette  ann&eacute;e encore, la Direction de la recherche, des &eacute;tudes, de l&rsquo;&eacute;valuation et des  statistiques (DREES) nous livre les r&eacute;sultats de son &eacute;tude sur les retrait&eacute;s et  les retraites. Elle porte sur l'ann&eacute;e&nbsp;2016.
<br>
<br>
Sans  surprise, le montant moyen de la pension brute de droit direct continue  d'augmenter pour s'&eacute;tablir &agrave; <strong>1&nbsp;389&nbsp;&euro; en d&eacute;cembre&nbsp;2016</strong> (1&nbsp;294&nbsp;&euro; nette de  pr&eacute;l&egrave;vements sociaux ; respectivement 1&nbsp;461&nbsp;&euro; et 1&nbsp;361&nbsp;&euro; pour les seuls r&eacute;sidents en France), soit une <strong>hausse de 0,4&nbsp;%</strong> en  euros constants par rapport &agrave; 2015. On ne peut, toutefois, affirmer avec  certitude que les retrait&eacute;s aient vraiment profit&eacute; de cette hausse. Elle  r&eacute;sulte, en r&eacute;alit&eacute;, du <strong>renouvellement de la population des retrait&eacute;s</strong> avec l&rsquo;arriv&eacute;e de nouveaux pensionn&eacute;s disposant de carri&egrave;res plus favorables et  de pensions en moyenne plus &eacute;lev&eacute;es et le d&eacute;c&egrave;s de retrait&eacute;s plus &acirc;g&eacute;s  percevant des pensions plus faibles. Pire encore, ceux qui b&eacute;n&eacute;ficiaient d&eacute;j&agrave;  d&rsquo;une pension ont subi une l&eacute;g&egrave;re perte de pouvoir d&rsquo;achat en raison de la <strong>non-revalorisation</strong> <strong>des pensions en 2016 </strong>(- 0,6&nbsp;% en euros constants). <br>
<br>
L'augmentation  des pensions en tant que telle ne suffit pas dans une logique d'assurance  vieillesse. Encore faut-il pouvoir garantir aux retrait&eacute;s un niveau de  ressources adapt&eacute; compte tenu de leur r&eacute;mun&eacute;ration professionnelle. Or, cet  objectif n'est pas atteint si on consid&egrave;re la <strong>baisse du taux de remplacement</strong> (d&eacute;fini comme le rapport entre le montant de la retraite &agrave; la liquidation et  celui du salaire en fin de carri&egrave;re) r&eacute;sultant d'un accroissement des salaires  plus fort que celui des pensions (74,9&nbsp;% pour les hommes et 74,7&nbsp;% pour les femmes, hors professions lib&eacute;rales).<br>
Malgr&eacute;  tout, le <strong>niveau de vie</strong> m&eacute;dian des personnes retrait&eacute;es reste l&eacute;g&egrave;rement  sup&eacute;rieur &agrave; celui de l&rsquo;ensemble de la population et leur taux de pauvret&eacute; est 2&nbsp;fois moins &eacute;lev&eacute; (6,6&nbsp;% contre 14,2&nbsp;%).
<br>
<br>
Si on  s'int&eacute;resse de plus pr&egrave;s aux profils des retrait&eacute;s, on s'aper&ccedil;oit que les <strong>unipensionn&eacute;s </strong>b&eacute;n&eacute;ficient en moyenne de pensions plus &eacute;lev&eacute;es de 8&nbsp;% que celle des  polypensionn&eacute;s (1/3 des retrait&eacute;s).<br>
De  m&ecirc;me, les <strong>femmes</strong> continuent de percevoir une pension inf&eacute;rieure &agrave; celle  des hommes, pr&eacute;cis&eacute;ment de 39&nbsp;% (25&nbsp;% si on tient compte des droits de  r&eacute;version pour lesquelles elles repr&eacute;sentent 9&nbsp;b&eacute;n&eacute;ficiaires sur 10). Ces  disparit&eacute;s trouvent leurs origines dans les &eacute;carts de r&eacute;mun&eacute;rations mais aussi  dans la moindre participation des femmes au march&eacute; du travail (les hommes cotisent  en moyenne 40&nbsp;trimestres de plus qu&rsquo;elles !). Fort heureusement, leur situation  tend &agrave; s&rsquo;am&eacute;liorer au fil des g&eacute;n&eacute;rations &nbsp;en raison de la hausse de leur taux d&rsquo;activit&eacute;, d&rsquo;une &eacute;l&eacute;vation  de leur niveau de qualification et de la mise en &oelig;uvre de dispositifs de  compensation des interruptions de carri&egrave;re li&eacute;es aux enfants (il faut dire qu'en 2004 l'&eacute;cart &eacute;tait de 45,5&nbsp;%).
<br>
<br>
Au-del&agrave;  des clivages &quot;unipensionn&eacute;s/polypensionn&eacute;s&quot; et &quot;hommes/femmes&quot;, <strong>les pensions diff&egrave;rent selon le r&eacute;gime</strong>. Si on consid&egrave;re une carri&egrave;re  compl&egrave;te dans les r&eacute;gimes de base, le montant des pensions de droit direct  varie de fa&ccedil;on significative :
    <ul class="ul">
      <li class="puce"><strong>salari&eacute;s</strong>&nbsp;:  1&nbsp;820&nbsp;&euro;,</li>
      <li class="puce"><strong>fonctionnaires  de l&rsquo;Etat, fonctionnaires affili&eacute;s &agrave; la CNRACL, et r&eacute;gimes sp&eacute;ciaux</strong>&nbsp;:  respectivement 2&nbsp;600&nbsp;&euro;, 1&nbsp;870&nbsp;&euro; et 2&nbsp;620&nbsp;&euro;,</li>
      <li class="puce"><strong>commer&ccedil;ants</strong> : 970&nbsp;&euro;,</li>
      <li class="puce"><strong>artisans </strong>: 1&nbsp;050&nbsp;&euro;,</li>
      <li class="puce"><strong>professions  lib&eacute;rales</strong> : 2&nbsp;460&nbsp;&euro;.
    </ul>
<br>

Par  rapport &agrave; 2015, le montant moyen de ces pensions a &eacute;volu&eacute; de fa&ccedil;on diff&eacute;rente selon  le r&eacute;gime d'affiliation. En effet, si elle augmente l&eacute;g&egrave;rement dans les r&eacute;gimes  de la CNAV et l&rsquo;IRCANTEC par rapport &agrave; 2015, elle demeure stable &agrave; l&rsquo;ARRCO et  diminue dans le RSI et la fonction publique de l&rsquo;Etat.<br>
Ces &eacute;carts  ne sont pas totalement injustifi&eacute;s puisqu&rsquo;ils refl&egrave;tent notamment les  diff&eacute;rences de revenus d&rsquo;activit&eacute; entre les personnes cotisant &agrave; ces diff&eacute;rents  r&eacute;gimes, la <strong>proportion des cadres et des personnes tr&egrave;s qualifi&eacute;es &eacute;tant  plus &eacute;lev&eacute;e dans les professions lib&eacute;rales et les m&eacute;tiers de la fonction  publique</strong>. C&rsquo;est d'ailleurs la raison pour laquelle, parmi les  polypensionn&eacute;s, les pensions sont les plus &eacute;lev&eacute;es pour ceux ayant comme r&eacute;gime  principal la fonction publique, les r&eacute;gimes sp&eacute;ciaux et les professions  lib&eacute;rales.
<br>
<br>
Il est  clair que de telles disparit&eacute;s entre les r&eacute;gimes ne peuvent que conforter les  partisans d'une <strong>r&eacute;forme syst&eacute;mique des retraites</strong>. A ce propos, rappelons  que le gouvernement a donn&eacute;, il y a un peu plus d'un mois, le coup d&rsquo;envoi de  ce grand chantier (voir notre <a href="../../nlp_2018/newsletter_18_04_26/newsletter_article_1.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent article</a>)  dont les enjeux sont de taille&nbsp;: les pensions de vieillesse et de survie  constituent &agrave; elles seules le <strong>premier poste de d&eacute;pense en protection sociale</strong> avec plus de 308 milliards d'euros vers&eacute;s &agrave; un peu plus de 17&nbsp;millions de retrait&eacute;s,  chiffre en constante augmentation (+&nbsp;0,9&nbsp;% en 2016).
<br>
<br>
Et la <strong>retraite  suppl&eacute;mentaire</strong> dans tout &ccedil;a ? <br>
Son  r&ocirc;le est justement de permettre de se constituer un compl&eacute;ment de revenu afin  de pallier les insuffisances des r&eacute;gimes obligatoires. Fin 2016, 12,7&nbsp;millions  de personnes d&eacute;tenaient un contrat de retraite suppl&eacute;mentaire (soit 4&nbsp;% en plus  qu&rsquo;en 2015) et 2,4&nbsp;millions de personnes ont per&ccedil;u des prestations issues d&rsquo;un  contrat de retraite suppl&eacute;mentaire. Malgr&eacute; ces chiffres encourageants, la  retraite suppl&eacute;mentaire <strong>reste marginale</strong>&nbsp;: la part des cotisations  vers&eacute;es &agrave; ce titre par rapport &agrave; l&rsquo;ensemble des cotisations acquitt&eacute;es &eacute;tant de  4,8&nbsp;% en 2016 et les prestations servies ne repr&eacute;sentent que 2&nbsp;% de l&rsquo;ensemble  des prestations retraite vers&eacute;es.<br>
On peut  penser que le gouvernement mettra tout en &oelig;uvre, &agrave; l&rsquo;occasion du <strong>projet de  loi PACTE</strong> (voir notre <a href="../../nlp_2018/newsletter_18_05_14/newsletter_article_1.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent article</a>),  pour redorer l&rsquo;image de l&rsquo;&eacute;pargne retraite aupr&egrave;s des Fran&ccedil;ais, surtout  lorsqu'on sait que la dur&eacute;e de carri&egrave;re (et donc de pr&eacute;paration &agrave; la retraite) repr&eacute;sente  une part de plus en plus &eacute;lev&eacute;e de la dur&eacute;e de vie totale au fil des g&eacute;n&eacute;rations  (les dur&eacute;es de carri&egrave;res ayant &eacute;volu&eacute; plus vite que les esp&eacute;rances de vie).
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://drees.solidarites-sante.gouv.fr/IMG/pdf/retraites_2018.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">DREES, les retraités et les retraites, éd. 2018, 16 mai 2018</a><br>
	</em>
	<br>
	<br>
