L&rsquo;administration fiscale a, dans une  publication urgente, actualis&eacute; le 9&nbsp;mai&nbsp;2018 ses commentaires concernant les r&eacute;gimes micro-BIC, micro-BNC  et le  r&eacute;gime sp&eacute;cifique du versement forfaitaire lib&eacute;ratoire pouvant s&rsquo;appliquer, sur  option, dans le cadre de ces r&eacute;gimes.<br>
Cette actualisation se limite &agrave; int&eacute;grer les  modifications l&eacute;gislatives ayant impact&eacute; les impositions des entreprises  jusqu&rsquo;en 2016 (mesures vot&eacute;es de 2013 &agrave; 2016). Les derni&egrave;res modifications  issues de la loi de finances pour 2018 ayant significativement augment&eacute; les  seuils d'application de ces r&eacute;gimes ne sont pas encore int&eacute;gr&eacute;es mais  l'administration a annonc&eacute; leur prochaine mise en ligne.
<br>
<br>
<strong>Note</strong> :<em> Ces mesures, y compris celles vot&eacute;es dans  le cadre de la loi de finances pour 2018 sont d'ores et d&eacute;j&agrave; int&eacute;gr&eacute;es dans  votre Patrith&egrave;que.</em>
<br>
<br>
La doctrine se trouve ainsi mise &agrave; jour des  mesures suivantes. <br>
La loi de finances rectificative pour 2013 a am&eacute;nag&eacute; les  r&egrave;gles relatives &agrave; l'appr&eacute;ciation des diff&eacute;rents r&eacute;gimes d'imposition  applicables aux BIC, BNC et BA (r&eacute;gime de l'auto-entrepreneur, des  micro-entreprises, de la franchise en base de TVA, r&eacute;gime r&eacute;el simplifi&eacute;...). Depuis  2015, les<strong> limites d'application</strong> de  ces r&eacute;gimes ne sont plus <strong>revaloris&eacute;es</strong> tous les ans, mais <strong>tous les</strong> <strong>3&nbsp;ans</strong>, dans la m&ecirc;me proportion que  l'&eacute;volution triennale du bar&egrave;me de l'IR. Ces limites <strong>s'appr&eacute;cient par rapport au chiffre d'affaires r&eacute;alis&eacute; l'ann&eacute;e  pr&eacute;c&eacute;dente</strong> et non au cours de l'ann&eacute;e m&ecirc;me.<br>
<br>
Par ailleurs, alors que la loi de finances rectificative  pour 2013 avait modifi&eacute; les r&egrave;gles de passage des r&eacute;gimes micro (y compris  auto-entrepreneur) au r&eacute;gime r&eacute;el en cas de<strong> franchissement des seuils</strong> en les alignant sur celles applicables en mati&egrave;re  de TVA &agrave; compter de 2015, la loi relative &agrave; l'artisanat, au commerce et aux TPE  est revenue sur ces nouvelles r&egrave;gles avant leur application en permettant le <strong>maintien des r&eacute;gimes micro </strong>(micro BIC,  r&eacute;gime d&eacute;claratif sp&eacute;cial et microtaxation)<strong> l'ann&eacute;e de soumission &agrave; la TVA</strong>, r&eacute;tablissant ainsi une ann&eacute;e de d&eacute;calage  entre la soumission &agrave; la TVA et la sortie des r&eacute;gimes micro-fiscaux. Ces  am&eacute;nagements se sont appliqu&eacute;s aux exercices clos et aux p&eacute;riodes d'imposition  arr&ecirc;t&eacute;es &agrave; compter du 31&nbsp;d&eacute;cembre&nbsp;2015. Par ailleurs, cette loi a rendu <strong>automatique l'application du r&eacute;gime  micro-social </strong>aux entreprises b&eacute;n&eacute;ficiant du r&eacute;gime fiscal des  micro-entreprises (BIC et BNC) ou de l'auto-entrepreneur &agrave; compter des  cotisations dues au titre de l'ann&eacute;e&nbsp;2016.<br>
<br>
Enfin, la loi relative &agrave; la transparence, &agrave; la lutte contre  la corruption et &agrave; la modernisation de la vie &eacute;conomique a, d'une part, <strong>supprim&eacute; l'exclusion des EURL </strong>dont  l'associ&eacute; unique est une personne physique des r&eacute;gimes micro-BIC et micro-BNC  (depuis le 11&nbsp;d&eacute;cembre&nbsp;2016) et, d'autre part,<strong> r&eacute;duit le d&eacute;lai d'option</strong> pour un r&eacute;gime r&eacute;el d'imposition de 2 &agrave;<strong> 1&nbsp;an </strong>(depuis&nbsp;2016).<br>
<br>
L'administration  fiscale reviendra prochainement sur les derniers am&eacute;nagements des r&eacute;gimes micro  consistant en l'augmentation significative, d&egrave;s l'imposition des revenus&nbsp;2017  (voir notre <a href="../../dossiers/lf_2018/lf2018_7.asp#SEUIL_MICRO" class="lien_intro_souligne">dossier sp&eacute;cial</a>), des limites  d'application de ces r&eacute;gimes pass&eacute;s&nbsp;:
<ul class="ul">
<li class="puce"><strong>de 82&nbsp;200&nbsp;&euro; &agrave; 170&nbsp;000&nbsp;&euro;</strong> pour les  activit&eacute;s de vente de marchandises, de vente &agrave; consommer sur place ou de  fourniture de logement (hors location meubl&eacute;e autres que meubl&eacute; de tourisme et  chambre d&rsquo;h&ocirc;te)&nbsp;; </li>
<li class="puce"><strong>de 32&nbsp;900&nbsp;&euro; &agrave; 70&nbsp;000&nbsp;&euro; </strong>pour les  activit&eacute;s de prestations de services relevant des BIC et pour les activit&eacute;s  relevant des BNC.
    </ul>
    <br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://bofip.impots.gouv.fr/bofip/9476-PGP?branch=2','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">BOFiP-Impôts, BNC - BIC - Harmonisation et simplification des régimes d'imposition des petites entreprises, 9 mai 2018</a><br>
	</em>
	<br>
	<br>