Alors que les commentaires de l'administration fiscale au  BOFiP se font toujours attendre &agrave; 1&nbsp;mois de la 1&egrave;re &eacute;ch&eacute;ance  pr&eacute;vue pour d&eacute;clarer l'IFI (17&nbsp;mai pour la d&eacute;claration papier, au cours  des semaines suivantes pour les t&eacute;l&eacute;d&eacute;clarants), le gouvernement vient, au  d&eacute;tour du lancement de la campagne d&eacute;clarative&nbsp;2018 (voir notre <a href="../../nlp_2018/newsletter_18_04_13/newsletter_article_1.asp" class="lien_intro_souligne">newsletter &agrave;  ce sujet pour plus de d&eacute;tails</a>), de livrer une <strong>1&egrave;re pr&eacute;cision</strong> sur les <strong>modalit&eacute;s de prise en compte</strong> <strong>au  passif de certaines dettes</strong>. Et il s'agit d'une <strong>mauvaise nouvelle</strong> pour les redevables qui sont propri&eacute;taires de leur  logement.
<br>
<br>
En effet, les <strong>dettes  aff&eacute;rentes &agrave; la r&eacute;sidence principale</strong> (cr&eacute;dits immobiliers et cr&eacute;dits  travaux notamment) et, plus g&eacute;n&eacute;ralement, toutes les dettes aff&eacute;rentes &agrave; des  biens b&eacute;n&eacute;ficiant d'un abattement l&eacute;gal pour leur imposition &agrave; l'IFI, devront  &ecirc;tre <strong>d&eacute;clar&eacute;es au passif</strong> dans la <strong>m&ecirc;me proportion</strong> que le bien auquel  elles se rattachent (et non plus en int&eacute;gralit&eacute;, comme c'&eacute;tait le cas en  mati&egrave;re d'ISF). En d'autres termes, pour reprendre l'exemple de la r&eacute;sidence  principale, le cr&eacute;dit ayant &eacute;t&eacute; souscrit pour financer son achat ne sera admis  au passif qu'&agrave; hauteur de <strong>70&nbsp;%</strong> -seulement- du montant restant d&ucirc; au 1er&nbsp;janvier de l'ann&eacute;e  d'imposition.
<br>
<br>
<strong>Note</strong> : <em>Le gouvernement profite &eacute;galement de cette  occasion pour rappeler que dans l'hypoth&egrave;se o&ugrave; un conjoint survivant est devenu  usufruitier d'un bien immobilier en vertu de la loi (et non d'une donation  entre &eacute;poux ou d'un testament), l'usufruitier et le(s) nu(s)-propri&eacute;taire(s)  devront d&eacute;clarer -chacun- la quote-part  de la valeur du bien lui appartenant (selon le bar&egrave;me fiscal). Cette r&egrave;gle  constitue un changement par rapport &agrave; l'ISF, car, pour rappel, la loi traitait  diff&eacute;remment les titulaires d'usufruit l&eacute;gaux selon que le conjoint &eacute;tait  d&eacute;c&eacute;d&eacute; avant ou apr&egrave;s le 1er&nbsp;juillet&nbsp;2002 car en ce dernier  cas, seul l'usufruitier devait d&eacute;clarer le bien, pour sa valeur en pleine  propri&eacute;t&eacute;.</em>
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('https://www.economie.gouv.fr/files/files/Actus2018/ir-dp-web02.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Dossier de presse, "2018, Impôts sur les revenus 2017", 10 avr. 2018</a><br>
	</em>
	<br>
	<br>
