Interrog&eacute;, dans le cadre d&rsquo;une question prioritaire de  constitutionnalit&eacute; (QPC), sur le r&eacute;gime d&eacute;rogatoire applicable aux plus-values  de valeurs mobili&egrave;res r&eacute;alis&eacute;es lors de partages successoraux, et notamment sur l&rsquo;absence de prise en  compte de la soulte vers&eacute;e par l&rsquo;attributaire lors de la revente du bien, le  Conseil constitutionnel a d&eacute;clar&eacute; le 13 juillet dernier le dispositif conforme  &agrave; la Constitution. <br>
Pour rappel, l&rsquo;op&eacute;ration de partage est un acte mettant fin  &agrave; l&rsquo;indivision. Lorsque la r&eacute;partition du bien indivis se fait de mani&egrave;re  in&eacute;galitaire entre les indivisaires, le partage donne lieu au versement d&rsquo;une  soulte, par l&rsquo;attributaire du bien indivis, aux autres copartageants, en  contrepartie de la cession de leurs droits sur le bien.</p>

<p>Selon le <strong>droit  commun</strong>, lorsqu&rsquo;une telle op&eacute;ration porte sur des valeurs mobili&egrave;res, des  droits sociaux ou des titres assimil&eacute;s, les copartageants sont impos&eacute;s &agrave;  l&rsquo;imp&ocirc;t sur le revenu sur le gain r&eacute;alis&eacute; du fait de la cession de leurs parts  de ces biens &agrave; l&rsquo;attributaire de ceux-ci. <br> L&rsquo;attributaire est quant &agrave; lui impos&eacute; ult&eacute;rieurement, au  moment de la cession des biens re&ccedil;us lors du partage. Pour le calcul de la  plus-value r&eacute;alis&eacute;e, il peut d&eacute;duire la soulte pr&eacute;c&eacute;demment vers&eacute;e.<br> A c&ocirc;t&eacute; de ce r&eacute;gime classique existe un <strong>r&eacute;gime d&eacute;rogatoire</strong>, s&rsquo;appliquant aux  partages portant &eacute;galement sur des valeurs mobili&egrave;res, des droits sociaux ou  des titres assimil&eacute;s mais issus d&rsquo;une <strong>indivision  successorale</strong>, conjugale ou entre partenaires d&rsquo;un PACS. <br> 
Ce r&eacute;gime sp&eacute;cifique pr&eacute;voit l&rsquo;exon&eacute;ration des gains r&eacute;alis&eacute;s  par les indivisaires lors du partage. En revanche, l&rsquo;attributaire du bien  indivis, lors de la cession ult&eacute;rieure du bien acquis, </strong>n&rsquo;est pas en droit de d&eacute;duire de sa plus-value la soulte</strong> vers&eacute;e aux  autres indivisaires.</p>
<p>La question pos&eacute;e au Conseil constitutionnel avait pour  objet principal de savoir si la diff&eacute;rence de traitement de la plus-value  r&eacute;alis&eacute;e par l&rsquo;attributaire du bien, selon que l&rsquo;indivision avait une <strong>origine conventionnelle ou successorale</strong>,  constituait une violation des principes constitutionnels d&rsquo;&eacute;galit&eacute; devant la  loi et devant les charges publiques.</p>
Retenant notamment l&rsquo;argument  selon lequel des traitements diff&eacute;rents pouvaient &ecirc;tre appliqu&eacute;s &agrave; des  situations diff&eacute;rentes et justifiant l&rsquo;imposition d&eacute;rogatoire de l&rsquo;attributaire  par l&rsquo;&eacute;conomie d&rsquo;ensemble du r&eacute;gime de partage successoral, le Conseil  constitutionnel a r&eacute;pondu par la n&eacute;gative et d&eacute;clar&eacute; le dispositif <strong>conforme &agrave; la Constitution.</strong> <br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000037193423&dateTexte=&categorieLien=id','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Ccel., 13 juill. 2018, n° 2018-719 QPC</a><br>
	</em>
	<br>
	<br>