Les contribuables ont droit &agrave; une <strong>exon&eacute;ration</strong> de plus-values immobili&egrave;res  pour la <strong>vente de leur r&eacute;sidence  principale</strong> mais uniquement s'il s'agit bien de leur r&eacute;sidence principale au  jour de la vente. Un couple vient d'en faire l'am&egrave;re exp&eacute;rience.
<br>
En effet, le 6&nbsp;juillet&nbsp;2004, ils  d&eacute;cident de vendre leur r&eacute;sidence principale mais par lots. Ils divisent l'immeuble  en diverses parcelles : <strong>2&nbsp;vendues</strong> au  titre d'une promesse de vente synallagmatique accompagn&eacute;e de conditions  suspensives et <strong>1</strong>&nbsp;(les combles)  qu'ils souhaitent <strong>conserver</strong> pour en  faire leur nouvelle r&eacute;sidence principale. Le temps d'am&eacute;nager les combles, ils <strong>r&eacute;sident dans un des 2&nbsp;lots destin&eacute;s &agrave; la  vente</strong>. <strong>L'autre reste inhabit&eacute;</strong> (aucune  activit&eacute; &eacute;lectrique n'y est d&eacute;tect&eacute;e, il n'est m&ecirc;me pas habitable). Le couple  pense pouvoir b&eacute;n&eacute;ficier de l'exon&eacute;ration pour tous les lots mais  l'administration fiscale ne l'entend pas de cette oreille. Elle redresse le  couple qui d&eacute;cide alors d'aller se d&eacute;fendre devant les tribunaux.
<br>
Le Conseil d'Etat juge que le <strong>lot rest&eacute; vacant ne peut &ecirc;tre consid&eacute;r&eacute;  comme leur r&eacute;sidence principale au moment de la vente</strong> car m&ecirc;me si la  promesse de vente vaut vente, le fait qu'il existe des conditions suspensives  repousse la date de la cession &agrave; leur <strong>r&eacute;alisation  effective</strong>. A cette date, le lot c&eacute;d&eacute; est rest&eacute; vacant durant plus d'un an,  m&ecirc;me s'il s'agissait auparavant d'une partie de la r&eacute;sidence principale du  couple il ne peut &ecirc;tre consid&eacute;r&eacute; comme tel au jour de la vente. Seul peut donc  b&eacute;n&eacute;ficier de l'exon&eacute;ration d'imposition le lot que les contribuables  habitaient durant l'am&eacute;nagement des combles.
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('https://www.legifrance.gouv.fr/affichJuriAdmin.do;jsessionid=2207F8A49D17F2BCDDFDD37EBF7CF4DB.tplgfr36s_3?oldAction=rechExpJuriAdmin&idTexte=CETATEXT000036086486&fastReqId=1507312392&fastPos=784','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">CE, n° 396209, 24 nov. 2017</a><br>
	</em>
	<br>
	<br>