Un chantier en vue de soutenir et  encourager le d&eacute;veloppement des entreprises fran&ccedil;aises a &eacute;t&eacute; ouvert par le  ministre de l'Economie et des Finances &agrave; l'automne dernier par la consultation  de plusieurs organisations professionnelles, parlementaires mais aussi chefs  d'entreprises sur ce sujet. D'apr&egrave;s un dossier de presse publi&eacute; par Bercy le  21&nbsp;d&eacute;cembre&nbsp;2017, au cours de cette 1&egrave;re &eacute;tape, pr&egrave;s de 38&nbsp;organisations ont formul&eacute; 980&nbsp;propositions. C'est sur la base de ces  contributions, qu'un <strong>plan d'action pour  la croissance et la transformation des entreprises (&quot;PACTE&quot;)</strong> a vu  le jour &quot;. Ce plan est soumis &agrave; <strong>consultation  publique</strong>, <strong>entre le 15&nbsp;janvier  et le 5&nbsp;f&eacute;vrier&nbsp;2018</strong>. Une fois cette 2&egrave;me &eacute;tape  achev&eacute;e, le gouvernement s'att&egrave;lera &agrave; la <strong>r&eacute;daction  d'un projet de loi au printemps&nbsp;2018</strong>.
<br>
<br>
La consultation publique repose  sur 9&nbsp;actions pour les entreprises, chaque action se composant de plusieurs  propositions qui peuvent &ecirc;tre accept&eacute;es, refus&eacute;es ou m&ecirc;me comment&eacute;es par les  participants. Outre des objectifs de simplification des d&eacute;marches  administratives visant &agrave; encourager la cr&eacute;ation d'entreprises, certaines  propositions visent &agrave; <strong>faciliter le  financement des entreprises </strong>et notamment&nbsp;:
<ul class="ul">
<li class="puce">simplifier  l'acc&egrave;s des PME aux march&eacute;s boursiers (simplification des obligations  r&eacute;glementaires li&eacute;es au statut d'entreprise cot&eacute;e par exemple),</li>
<li class="puce">encourager  les nouveaux investisseurs en renfor&ccedil;ant leur droit d'actionnaire minoritaire,</li>
<li class="puce">cr&eacute;er  un plan d'&eacute;pargne en actions (PEA) pour les jeunes (autorisation du  repr&eacute;sentant l&eacute;gal, montant plafonn&eacute; et sommes d&eacute;fiscalis&eacute;es jusqu'&agrave; la  majorit&eacute;),</li>
<li class="puce">orienter  l'&eacute;pargne des fran&ccedil;ais vers l'entreprise par le biais de l'assurance vie et des  produits d'&eacute;pargne retraite.
</ul>
<br>

S'agissant de l'assurance vie, il  est envisag&eacute; d'augmenter les possibilit&eacute;s pour les entreprises d'assurance de moduler <strong>la garantie en capital offerte sur les  fonds euros en fonction de leur dur&eacute;e</strong>&nbsp;: en cas de d&eacute;tention longue (8 &agrave; 10&nbsp;ans), la garantie serait bonifi&eacute;e, alors qu'elle serait r&eacute;duite en  cas de d&eacute;tention courte. Orienter ce produit vers le financement de l'&eacute;conomie  r&eacute;elle, tel serait le but recherch&eacute;.
<br>
Enfin, le gouvernement entend <strong>renforcer le recours &agrave; l'&eacute;pargne salariale</strong> dans les PME en simplifiant les formalit&eacute;s administratives et en mettant en  place, dans les entreprises de 11 &agrave; 49&nbsp;salari&eacute;s, un dispositif de partage de la  valeur, souple pour l'entreprise. En outre, il envisage un <strong>abaissement du forfait social </strong>d'une part, pour les petites  entreprises et d'autre part, pour toutes les autres lorsque les versements sont  investis en priorit&eacute; dans un plan d'&eacute;pargne long terme (type &eacute;pargne retraite)  ou dans l'actionnariat salari&eacute;.
<br>
<br>
	<em><strong>Sources </strong>: <br>
	>&nbsp;<a href="javascript:var w=window.open('https://minefi.hosting.augure.com/Augure_Minefi/r/ContenuEnLigne/Download?id=083C5047-286B-4805-8F57-A6E81FD2231B&filename=295%20-%20CP%20Lancement%20de%20la%20consultation%20publique%20en%20ligne%20PACTE.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Lancement de la consultation publique sur le PACTE, 15&nbsp;janv.&nbsp;2018</a><br>
	>&nbsp;<a href="javascript:var w=window.open('https://www.pacte-entreprises.gouv.fr/project/consultation/consultation/consultation-9','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Consultation publique en ligne sur le PACTE</a><br>
	>&nbsp;<a href="javascript:var w=window.open('https://www.economie.gouv.fr/files/files/PDF/2018/Trame_de_la_consultation_PACTE.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Trame de consultation PACTE, 15 janv. 2018</a><br>
	>&nbsp;<a href="javascript:var w=window.open('https://minefi.hosting.augure.com/Augure_Minefi/r/ContenuEnLigne/Download?id=C89E8587-D182-400F-8E3A-A8D9B3AE995E&filename=272%20-%20DP%20PACTE.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Dossier de presse PACTE, 21 déc. 2017</a><br>
	</em>
	<br>
	<br>
