La loi Hamon du 17&nbsp;mars&nbsp;2014 a institu&eacute; le principe d'un <strong>droit de r&eacute;siliation des contrats  d'assurance emprunteur</strong> li&eacute;s &agrave; un pr&ecirc;t immobilier dans le d&eacute;lai de <strong>1 an</strong> &agrave; partir de la conclusion du  contrat. Ce principe, applicable depuis le 26&nbsp;juillet&nbsp;2014, a &eacute;t&eacute;  &eacute;tendu par une loi du 21&nbsp;f&eacute;vrier&nbsp;2017 qui pr&eacute;voit que les consommateurs peuvent <strong>r&eacute;silier leur contrat</strong>, en cours ou &agrave;  venir &agrave; partir du 1er&nbsp;janvier&nbsp;2018, <strong>&agrave; chaque date anniversaire</strong> de celui-ci.
<br>
Estimant que ces modifications portaient atteinte au  maintien de l'&eacute;conomie des conventions l&eacute;galement conclues, les nouvelles  dispositions s'appliquant notamment &agrave; tous les contrats en cours, la F&eacute;d&eacute;ration  Bancaire Fran&ccedil;aise (FBF) a soulev&eacute; une question pr&eacute;judicielle de  constitutionnalit&eacute; (QPC).
<br>
Selon la FBF, en permettant aux emprunteurs de r&eacute;silier leur  contrat d'assurance emprunteur annuellement, le l&eacute;gislateur aurait <strong>modifi&eacute; l'&eacute;quilibre des contrats</strong>. De  plus, l'atteinte port&eacute;e &agrave; ces contrats aurait un caract&egrave;re inconstitutionnel,  les dispositions litigieuses s'appliquant &agrave; l'ensemble des contrats, m&ecirc;me &agrave;  ceux en cours.<br>
A ces griefs, le Conseil constitutionnel r&eacute;pond par la  n&eacute;gative et d&eacute;clare ainsi <strong>conforme &agrave; la  Constitution</strong> le droit de r&eacute;siliation annuelle des contrats d'assurance  emprunteur dans le cadre d'un pr&ecirc;t immobilier.
<br>
Pour motiver leur d&eacute;cision, les Sages rappellent tout  d'abord que le l&eacute;gislateur a <strong>toujours la  possibilit&eacute; de modifier des textes ant&eacute;rieurs</strong>. Il ne peut cependant pas,  sans motif d'int&eacute;r&ecirc;t g&eacute;n&eacute;ral suffisant, porter atteinte aux situations  l&eacute;galement acquises ou remettre en cause les effets attendus de ces situations.
<br>
A ce titre, dans le cas d'esp&egrave;ce, les Sages font remarquer  qu'aucune disposition de droit applicable avant ces nouvelles dispositions  n'avait pu faire na&icirc;tre une attente l&eacute;gitime des &eacute;tablissements bancaires et  des soci&eacute;t&eacute;s d'assurance quant &agrave; la p&eacute;rennit&eacute; des conditions de r&eacute;siliation de  leurs contrats d'assurance, ces conditions ayant d&eacute;j&agrave; fait l'objet de plusieurs  modifications l&eacute;gislatives par le pass&eacute; sans qu'aucune action n'ait &eacute;t&eacute;  intent&eacute;e contre elles.
<br>
En outre, le Conseil constitutionnel indique qu'en adoptant  ces nouvelles dispositions, le l&eacute;gislateur a poursuivi un <strong>objectif d'int&eacute;r&ecirc;t g&eacute;n&eacute;ral</strong> qui ne peut &ecirc;tre remis en cause : il a voulu renforcer la protection des consommateurs en assurant un <strong>meilleur &eacute;quilibre contractuel</strong> et permettre  au plus grand nombre d'emprunteurs de b&eacute;n&eacute;ficier de ce nouvel &eacute;quilibre <strong>en visant, en plus des contrats conclus &agrave;  partir du 1er&nbsp;janvier&nbsp;2018, tous les contrats en cours</strong> du fait  de la longue dur&eacute;e de ces contrats.
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://www.conseil-constitutionnel.fr/conseil-constitutionnel/root/bank/download/2017685QPC2017685qpc.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">C. Cons., n° 2017-685 QPC, 12 janv. 2018</a><br>
	</em>
	<br>
	<br>