A l'aune d'une nouvelle r&eacute;forme des retraites et, compte tenu des derni&egrave;res  donn&eacute;es du COR (Conseil d'orientation des retraites) laissant pr&eacute;sager une  baisse du niveau de vie des retrait&eacute;s et du taux de remplacement, le COR revoit  les donn&eacute;es issues de ses travaux consacr&eacute;s &agrave; l'&eacute;pargne retraite pr&eacute;sent&eacute;s en  juillet&nbsp;2015 et analyse, par la m&ecirc;me occasion, les comportements d'&eacute;pargne des  fran&ccedil;ais.
<br>
<br>
Alors que 70&nbsp;% des fran&ccedil;ais se disent inquiets pour leur retraite, le recours aux  dispositifs d'&eacute;pargne retraite reste plut&ocirc;t rare en France. Il existe pourtant <strong>une  grande vari&eacute;t&eacute; de produits</strong>, lesquels peuvent &ecirc;tre souscrits &agrave; titre  professionnel ou priv&eacute;, &agrave; cotisations ou prestations d&eacute;finies, et dont la  fiscalit&eacute; est attractive tout au long de la phase d'&eacute;pargne ou au moment de la  perception des prestations. Malgr&eacute; tout, <strong>certains des produits s'&eacute;loignent  du principe m&ecirc;me d'&eacute;pargne retraite</strong>. Tel est le cas du PERCO et du PERP qui  proposent, en plus des possibilit&eacute;s de d&eacute;blocage anticip&eacute; propres aux produits  d'&eacute;pargne retraite, une sortie en capital (soit en totalit&eacute; soit de fa&ccedil;on  partielle) allant &agrave; l'encontre m&ecirc;me de la mutualisation du risque de long&eacute;vit&eacute;.
<br>
<br>
Les  &eacute;tudes du COR d&eacute;montrent que <strong>les dispositifs d'&eacute;pargne retraite restent  encore marginaux</strong> par rapport &agrave; l'ensemble des r&eacute;gimes l&eacute;galement  obligatoires ou suppl&eacute;mentaires, puisque les cotisations vers&eacute;es sur ces  supports ne repr&eacute;sentent que 4,3&nbsp;% de l'ensemble des cotisations acquitt&eacute;es au  titre de la retraite, et les prestations, seulement 1,9&nbsp;% de l'ensemble des  prestations vers&eacute;es. A titre de comparaison, les provisions math&eacute;matiques  (engagements des assureurs &agrave; l'&eacute;gard des souscripteurs) au titre de la retraite  s'&eacute;l&egrave;vent &agrave; 207&nbsp;milliards&nbsp;&euro; contre 1&nbsp;600&nbsp;milliards&nbsp;&euro; pour l'assurance vie.
<br>
Parmi les  facteurs explicatifs, le Conseil rel&egrave;ve les <strong>particularit&eacute;s de notre syst&egrave;me  de retraite</strong>. En effet, dans un syst&egrave;me de retraite par r&eacute;partition, le  revenu disponible des actifs est amput&eacute; des contributions finan&ccedil;ant le syst&egrave;me  de retraite diminuant ainsi la capacit&eacute; d'&eacute;pargne des assur&eacute;s. En outre, les  jeunes &eacute;pargnants, sont davantage attir&eacute;s par la flexibilit&eacute; que ne satisfait  pas les produits d'&eacute;pargne retraite en tant que produit &quot;tunnel&quot; (les  sommes &eacute;tant bloqu&eacute;es jusqu'au d&eacute;part en retraite). Ils orientent alors leur  &eacute;pargne en priorit&eacute; vers l&rsquo;acquisition du logement ou pour se pr&eacute;munir contre  un &eacute;v&egrave;nement inattendu.
<br>
<br>
Au-del&agrave;,  il apparait que le taux de d&eacute;tention de l&rsquo;&eacute;pargne retraite cro&icirc;t avec le niveau  de revenu, l&rsquo;&acirc;ge et le niveau d&rsquo;&eacute;ducation. Par rapport aux autres cat&eacute;gories  sociales, les ind&eacute;pendants y sont plus sensibles et &eacute;pargnent davantage en vue  de la retraite. N&eacute;anmoins, les alternatives existant aux produits d'&eacute;pargne  retraite, parmi lesquelles <strong>l'assurance vie</strong> -notamment les contrats en  euros- sont <strong>privil&eacute;gi&eacute;es</strong> par les m&eacute;nages fran&ccedil;ais. <strong>Attention  toutefois &agrave; la rentabilit&eacute;</strong> de ces contrats. En effet, le Conseil met  l'accent sur le fait que les assureurs ne peuvent pas d&eacute;tenir des actifs  susceptibles de fournir une rentabilit&eacute; &eacute;lev&eacute;e &agrave; long terme -&agrave; savoir, des  actions- et privil&eacute;gient les placements obligataires moins risqu&eacute;s.
<br>
<br>
Au final, il serait opportun d'<strong>encourager les comportements d'&eacute;pargne retraite </strong>des  fran&ccedil;ais compte tenu de la situation financi&egrave;re des r&eacute;gimes obligatoires et de  la baisse du niveau de vie des retrait&eacute;s. Des solutions devraient &ecirc;tre  propos&eacute;es en ce sens dans le cadre du <strong>plan d'action pour la croissance et la transformation des entreprises</strong> lanc&eacute; d&egrave;s fin&nbsp;2017 (voir notre <a href="http:../../nlp_2018/newsletter_18_01_31/newsletter_article_2.asp">newsletter</a>).
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://www.cor-retraites.fr/IMG/pdf/doc-4143.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">COR - L'épargne  en vue de la retraite, janv. 2018</a><br>
	</em>
	<br>
	<br>
