Le <strong>taux &quot;normal&quot; de CSG</strong> applicable aux <strong>pensions de retraite</strong> a &eacute;t&eacute; <strong>relev&eacute;  de 1,7&nbsp;point</strong> au 1er&nbsp;janvier&nbsp;2018. Il est ainsi  d&eacute;sormais fix&eacute; &agrave; 8,3&nbsp;% (contre 6,6&nbsp;% avant l'adoption de la <a href="../../dossiers/lfss_2018/lfss2018_2.asp#CSG_AUGMENT" class="lien_intro_souligne">LFSS  pour 2018</a>.  Ce ne sont pas les seuls revenus concern&eacute;s par cette hausse mais, contrairement  aux salari&eacute;s par exemple, cette augmentation s'est faite sans compensation. Les  salari&eacute;s du secteur priv&eacute; ont effectivement pu constater sur leur fiche de paie  du mois de janvier que leurs cotisations sociales avaient baiss&eacute; de 2,2&nbsp;points  par l'effet conjugu&eacute; de la suppression de la cotisation d'assurance maladie de  0,75&nbsp;% et de la baisse de 1,45&nbsp;point de la cotisation d'assurance ch&ocirc;mage  (qui reste due &agrave; hauteur de 0,95&nbsp;%, mais dont la suppression a elle aussi  &eacute;t&eacute; <a href="../../dossiers/lfss_2018/lfss2018_2.asp#BAISSE_COTIS" class="lien_intro_souligne">programm&eacute;e pour octobre&nbsp;2018</a>).
<br>
<br>
<strong>Note</strong> : <em>Les retrait&eacute;s dont le  revenu fiscal de r&eacute;f&eacute;rence n'exc&egrave;de pas 14&nbsp;404&nbsp;&euro; n'ont pas &eacute;t&eacute;  impact&eacute;s par cette hausse de CSG, leurs pensions de retraite &eacute;tant soumises au  taux r&eacute;duit -et inchang&eacute;- de CSG de 3,8&nbsp;%.</em>
<br>
<br>
Suite aux nombreuses critiques de  retrait&eacute;s s'estimant l&eacute;s&eacute;s par la hausse -<strong>sans  compensation</strong>- du taux de CSG applicable &agrave; leurs pensions de retraite, le <strong>Premier ministre</strong> a annonc&eacute;, le 20&nbsp;mars  dernier, qu'un <strong>geste</strong> allait &ecirc;tre  fait <strong>en faveur des retrait&eacute;s</strong> dont le <strong>revenu fiscal de r&eacute;f&eacute;rence exc&egrave;de de peu  le seuil de 14&nbsp;404&nbsp;&euro;</strong>. Cette mesure qui devrait int&eacute;resser moins de  1&nbsp;% des retrait&eacute;s concern&eacute;s par la hausse (le gouvernement annonce que la  mesure b&eacute;n&eacute;ficiera &agrave; 100&nbsp;000&nbsp;m&eacute;nages sur 7,5&nbsp;millions de retrait&eacute;s impact&eacute;s),  devrait &ecirc;tre inscrite dans le <strong>projet de  loi de financement de la S&eacute;curit&eacute; sociale pour 2019</strong>, qui sera pr&eacute;sent&eacute; au  Parlement en octobre prochain.
<br>
<br>
	<em><strong>Source </strong>: Allocution télévisée, interview du Premier ministre, 20 mars 2018<br>
	</em>
	<br>
	<br>
