Avant de  s'attaquer &agrave; la r&eacute;forme structurelle des retraites en 2019, <strong>le gouvernement envisage de refondre  l'&eacute;pargne retraite</strong> dans le cadre du plan d'action pour la croissance et la transformation des entreprises (PACTE) dont le projet de loi devrait &ecirc;tre  discut&eacute; ce printemps (voir notre <a href="../../nlp_2018/newsletter_18_01_31/newsletter_article_2.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent article</a>).  Profitant de cette dynamique, la <strong>F&eacute;d&eacute;ration  Fran&ccedil;aise de l'Assurance</strong> (FFA) entend apporter sa pierre &agrave; l'&eacute;difice en  avan&ccedil;ant ses <strong>id&eacute;es pour une retraite  suppl&eacute;mentaire simplifi&eacute;e</strong> favorisant le financement de l'&eacute;conomie  productive.
<br>
<br>
Lors d'une  conf&eacute;rence de presse donn&eacute;e le 15&nbsp;mars dernier, la F&eacute;d&eacute;ration n'a pas h&eacute;sit&eacute; &agrave;  mettre l'accent sur les failles de notre syst&egrave;me de retraite et notamment sur  le fait qu'il repose &agrave; 98&nbsp;% sur la r&eacute;partition, exposant les actifs des  &eacute;pargnants en cas de r&eacute;cession &eacute;conomique. Au contraire, la FFA pr&ocirc;ne le  financement par capitalisation encore peu repr&eacute;sent&eacute; en France (2&nbsp;% contre 15&nbsp;%  en moyenne pour les pays de l'OCDE) et propose, en ce sens, que soit <strong>cr&eacute;&eacute;e une</strong> <strong>assurance retraite pour un compl&eacute;ment de revenu &agrave; vie</strong> r&eacute;pondant au  nom de code &quot;<strong>REVAVIE</strong>&quot;.
<br>
<br>
La solution  apport&eacute;e par la F&eacute;d&eacute;ration&nbsp; consiste en  r&eacute;alit&eacute;, en la mise en place d&rsquo;un produit <strong>accessible  &agrave; tous</strong> avec des<strong> r&egrave;gles techniques  identiques quel que soit le statut professionnel</strong> (salari&eacute;, ind&eacute;pendant,  fonctionnaire&hellip;). L'id&eacute;e serait de <strong>converger  &agrave; terme vers un syst&egrave;me uniforme </strong>(notons que le PERCO ne serait pas  concern&eacute;, car consid&eacute;r&eacute; comme un produit d'&eacute;pargne salariale). Ainsi, &agrave;  l'instar des dispositifs actuels, il offrirait un compl&eacute;ment de revenus garanti  pour la vie et inclurait une <strong>option  d&eacute;pendance</strong>. En cas de coup dur, l&rsquo;adh&egrave;rent aurait la garantie de r&eacute;cup&eacute;rer  son &eacute;pargne. Le <strong>caract&egrave;re portable</strong> du produit permettrait de conserver l&rsquo;actif sans p&eacute;nalit&eacute; en cas de changement dans  la vie professionnelle. Enfin, les adh&eacute;rents auraient la possibilit&eacute; de<strong> transf&eacute;rer leur contrat </strong>d'un assureur  &agrave; un autre en toute simplicit&eacute;. <br>
Avec ce  nouveau dispositif, la FFA pr&eacute;tend apporter plus de justice entre les  g&eacute;n&eacute;rations et davantage de financement des entreprises en fonds propres.
<br>
<br>
<strong>Note</strong> :<em> Le gouvernement s'inspirera sans doute des caract&eacute;ristiques du REVAVIE  pour mettre au point le &quot;Compte Avenir&quot;, dispositif visant &agrave; unifier  les produits d'&eacute;pargne retraite qui figure au rang des mesures propos&eacute;es dans  le cadre du PACTE.</em>
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://www.patritheque.fr/sources/divers/18.03.15_conference_de_presse_15_mars_2018.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">FFA, Bilan de l'année 2017 et perspectives 2018, 15 mars 2018</a><br>
	</em>
	<br>
	<br>
