A l'occasion du Forum &quot;Entreprises  en action(s) !&quot; qui a lieu le 28&nbsp;mars&nbsp;2018 &agrave; Bercy, le ministre de l'Economie et des Finances a communiqu&eacute; de nouvelles informations sur le <strong>projet de loi pour la croissance et la  transformation des entreprises (ou &quot;PACTE&quot;)</strong> en cours de  pr&eacute;paration (voir notre <a href="../../nlp_2018/newsletter_18_01_31/newsletter_article_2.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent article</a>). Ce projet de loi, qui devrait &ecirc;tre pr&eacute;sent&eacute; tr&egrave;s prochainement en Conseil des  ministres, devrait contenir diff&eacute;rentes propositions visant &agrave; mobiliser  davantage l'&eacute;pargne des m&eacute;nages en faveur du financement des entreprises.  Ainsi, seraient notamment mis &agrave; contribution l'&eacute;pargne retraite, l'assurance  vie et le PEA-PME.
<br>
<br>
<span class="titre_2">Epargne retraite</span>
<br>
<br>
Avec plus de 200 milliards &euro;  d'encours, l'<strong>&eacute;pargne retraite</strong> est de  plus en plus sollicit&eacute;e par les Fran&ccedil;ais, mais reste encore marginale par  rapport &agrave; l'assurance vie. Pour y rem&eacute;dier, le gouvernement inscrit dans le  PACTE plusieurs mesures visant &agrave; r&eacute;former l'&eacute;pargne retraite et promouvoir  ainsi les diff&eacute;rents dispositifs existants. Ainsi, il <strong>introduirait une option par d&eacute;faut de gestion pilot&eacute;e</strong> permettant de  s&eacute;curiser l'&eacute;pargne &agrave; l'approche de l'&acirc;ge de la retraite et <strong>simplifierait les retraits </strong>des sommes &eacute;pargn&eacute;es  &agrave; l'&acirc;ge de la retraite. La <strong>portabilit&eacute;</strong> d'un produit &agrave; un autre serait, de surcro&icirc;t, am&eacute;lior&eacute;e (s'agissant, en  priorit&eacute;, du PERP, PERCO, contrat &quot;article 83&quot;, PERE et contrat  Madelin) afin de r&eacute;pondre au contexte actuel de mobilit&eacute; professionnelle.  Enfin, le recours aux produits d'&eacute;pargne retraite s'av&eacute;rerait <strong>moins co&ucirc;teux </strong>du fait de la <strong>baisse de 20 &agrave; 16&nbsp;% du taux du forfait  social</strong> lorsque les versements sont effectu&eacute;s dans des fonds investis pour  partie dans des actions de PME et des entreprises de taille interm&eacute;diaire (ETI)  et qui proposent par d&eacute;faut une gestion pilot&eacute;e.
<br>
<br>
<strong>Note</strong> : <em>A l'origine, il &eacute;tait  pr&eacute;vu d'unifier au sein d'un &quot;<strong>Compte  Avenir</strong>&quot; les diff&eacute;rents produits d'&eacute;pargne retraite. Il faudra sans  doute attendre les d&eacute;bats parlementaires sur projet de loi pour avoir plus de  pr&eacute;cisions sur le devenir de cette proposition.</em>
<br>
<br>
<span class="titre_2">Assurance vie, PEA et acc&egrave;s &agrave; la cote</span>
<br>
<br>
Le <strong>fonctionnement des fonds Euro-croissance</strong> -fonds se situant &agrave;  mi-chemin entre le fonds euros et les unit&eacute;s de comptes qui permettent d'obtenir  en principe une meilleure r&eacute;mun&eacute;ration que le fonds euros tout en limitant les  risques- serait <strong>simplifi&eacute;</strong> notamment  en ce qui concerne la communication sur leur rendement. De plus, la liste des  fonds &eacute;ligibles &agrave; l'assurance vie serait <strong>&eacute;tendue  aux fonds professionnels de capital investissement </strong>et le paiement des  contrats d'assurance vie en titres ou en parts de fonds de capital-risque  serait facilit&eacute;.<br>
Tout comme le fonds  Euro-croissance, le <strong>PEA-PME</strong> conna&icirc;t  depuis sa cr&eacute;ation en 2014 un succ&egrave;s commercial mitig&eacute; alors qu'il &eacute;tait  destin&eacute; &agrave; l'origine &agrave; favoriser l'investissement en fonds propres dans les PME  et les ETI. L'id&eacute;e consisterait &agrave; proposer aux &eacute;pargnants d'investir, via le  PEA-PME, dans des <strong>titres &eacute;mis dans le  cadre du financement participatif </strong>(titres participatifs, obligations &agrave; taux  fixe et minibons).<br>
Enfin, concernant l'acc&egrave;s des PME  aux march&eacute;s financiers, des <strong>simplifications  d'acc&egrave;s &agrave; la cotation</strong> seraient &eacute;galement envisag&eacute;es (seuil d'&eacute;tablissement  du prospectus, r&eacute;forme de la proc&eacute;dure de retrait obligatoire de la cote, etc.).
<br>
<br>
	<em><strong>Sources </strong>: <br>
	>&nbsp;<a href="javascript:var w=window.open('https://minefi.hosting.augure.com/Augure_Minefi/r/ContenuEnLigne/Download?id=8809D6F9-F5F4-4039-B3C9-078FF56FCF18&filename=Dossier%20de%20presse%20-%20Pacte%20-%20Entreprises%20en%20actions%20-%2028%20mars.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Dossier de presse "Forum entreprises en action(s) !", 28 mars 2018</a><br>
	>&nbsp;<a href="javascript:var w=window.open('https://minefi.hosting.augure.com/Augure_Minefi/r/ContenuEnLigne/Download?id=F1467CA7-337F-4212-B00B-723369DF08CD&filename=20180328%20-%20Discours%20BLM%20-%20Cl%C3%B4ture%20Forum%20Entreprises%20en%20actions.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Discours du Ministre de l'Economie, 28 mars 2018</a><br>
	</em>
	<br>
	<br>
