L'administration fiscale ne transige pas avec les  comportements d'optimisation fiscale li&eacute;s &agrave; &quot;l'<strong>ann&eacute;e blanche&quot;</strong> dans le cadre de la mise en place du pr&eacute;l&egrave;vement  &agrave; la source de l'IR (PAS). <br>
Elle vient d'en faire la d&eacute;monstration en r&eacute;pondant &agrave; un  d&eacute;put&eacute; qui s'inqui&eacute;tait du sort des auto-entrepreneurs qui, anticipant, le  passage au PAS en 2018, ont <strong>d&eacute;nonc&eacute; leur  option pour le r&eacute;gime de l'auto-entreprise fin 2016</strong>, et souhaiteraient  revenir r&eacute;troactivement sur ce choix qui ne pr&eacute;sente plus d'int&eacute;r&ecirc;t compte tenu  du report, par le gouvernement, de l'entr&eacute;e en vigueur du PAS en 2019. <br>
La r&eacute;ponse de l'administration est ferme : il n'y aura <strong>pas de mesure de tol&eacute;rance</strong> pour ces  exploitants qui <strong>ne pourront pas revenir  sur leur choix</strong> qui est &quot;davantage la manifestation d'un comportement  optimisant que d'une gestion normale de leur activit&eacute;&quot;.
<br>
<br>
<strong>Note</strong> : <em>Pour rappel, le r&eacute;gime de l'auto-entrepreneur  permet d'acquitter l'IR sous forme de pr&eacute;l&egrave;vements forfaitaires mensuels ou  trimestriels (au choix) calcul&eacute;s sur le chiffre d'affaires. <br>
Dans la mesure o&ugrave; ces revenus font l'objet d'un pr&eacute;l&egrave;vement contemporain  lib&eacute;ratoire de l'IR, ils n'ont pas &eacute;t&eacute; inclus dans le champ des revenus  concern&eacute;s par le PAS, et n'ouvrent ainsi pas droit au cr&eacute;dit d'imp&ocirc;t  modernisation du recouvrement (CIMR) permettant de neutraliser l'IR l'ann&eacute;e du  passage au PAS. <br>
Pour contourner cette r&egrave;gle, certains auto-entrepreneurs, anticipant l'entr&eacute;e  en vigueur du PAS au 1er&nbsp;janvier&nbsp;2018, ont donc d&eacute;nonc&eacute; leur option  pour le r&eacute;gime du versement lib&eacute;ratoire, d&egrave;s d&eacute;cembre&nbsp;2016, pour pouvoir b&eacute;n&eacute;ficier  du CIMR et donc de &quot;l'ann&eacute;e blanche&quot;. Cette d&eacute;nonciation s'est  trouv&eacute;e vid&eacute;e de sens du fait de la d&eacute;cision, prise par le Gouvernement, de  n'appliquer le PAS qu'&agrave; compter de 2019. Les entrepreneurs concern&eacute;s se  trouvant ainsi &quot;pi&eacute;g&eacute;s&quot; et p&eacute;nalis&eacute;s ont sollicit&eacute; le droit de se  replacer r&eacute;troactivement sous le r&eacute;gime de l'auto-entrepreneur au titre de  2017, ce que leur refuse l'administration.</em>
<br>
<br>
Par ailleurs, l'administration rappelle que la loi mettant  en place la PAS a pr&eacute;vu, plusieurs <strong>mesures  anti-abus</strong>, dont une &agrave; destination des <strong>auto-entrepreneurs,</strong> visant pr&eacute;cis&eacute;ment &agrave; &eacute;viter les comportements d&eacute;crits par le d&eacute;put&eacute; (d&eacute;nonciation  de l'option pour le versement lib&eacute;ratoire de l'imp&ocirc;t sur le revenu, afin de se  placer dans le champ du PAS dans l'unique dessein de b&eacute;n&eacute;ficier du CIMR et donc  de la neutralisation de l'IR). La loi pr&eacute;voit en effet que les contribuables,  qui <strong>d&eacute;noncent leur option en 2017</strong> pour 2018 et qui exercent une <strong>nouvelle  option </strong>pour le versement lib&eacute;ratoire en <strong>2018</strong> pour 2019, <strong>ne  b&eacute;n&eacute;ficieront pas du CIMR</strong>.
<br>
<br>
	<em><strong>Source </strong>: <a href="javascript:var w=window.open('http://www2.assemblee-nationale.fr/questions/detail/15/qe/4347/(vue)/pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">Rép. min. à M. Sempastous, n° 4347, JOANQ 20 mars 2018</a><br>
	</em>
	<br>
	<br>
