Alors que le gouvernement entend renforcer  l'&eacute;pargne retraite dans le cadre du projet de loi PACTE (voir notre <a href="http://www.patritheque.fr/nlp_2018/newsletter_18_05_14/newsletter_article_1.asp" class="lien_intro_souligne">pr&eacute;c&eacute;dent  article</a>),  l'Autorit&eacute; de contr&ocirc;le prudentiel et de r&eacute;solution (ACPR) alerte sur<strong> l'ampleur des sommes non r&eacute;clam&eacute;es </strong>par  les b&eacute;n&eacute;ficiaires et sur les <strong>difficult&eacute;s  li&eacute;es &agrave; la fiabilit&eacute; des fichiers clients des assureurs</strong>. 
<br>
<br>
Rappelez-vous, la <a href="http://www.patritheque.fr/dossiers-archives/Sapin2/Sapin2_3.asp#RETRAITE" class="lien_intro_souligne">loi Sapin</a> a introduit, sans en d&eacute;finir pr&eacute;cis&eacute;ment les contours, une<strong> obligation annuelle et sp&eacute;cifique d&rsquo;information des assur&eacute;s</strong> de  contrats d&rsquo;assurance vie dont les prestations sont li&eacute;es &agrave; la cessation  d&rsquo;activit&eacute; professionnelle. Les assureurs sont tenus par cette obligation &agrave;  l'&eacute;gard des <strong>assur&eacute;s ayant d&eacute;pass&eacute; la  date de liquidation de leur pension</strong> dans un r&eacute;gime obligatoire d'assurance  vieillesse <strong>ou, &agrave; d&eacute;faut, l&rsquo;&acirc;ge de d&eacute;part  &agrave; la retraite</strong>. L'ACPR devait remettre au Parlement, avant le 1er juin 2018,  un rapport pr&eacute;sentant, pour les ann&eacute;es 2016 et 2017, un bilan d&eacute;crivant les  actions men&eacute;es pour contr&ocirc;ler le respect de cette obligation d'information.
<br>
<br>
Pour ce faire, elle a men&eacute; une  enqu&ecirc;te aupr&egrave;s de 17 organismes assureurs repr&eacute;sentant pr&egrave;s de 80&nbsp;% du  march&eacute; et analys&eacute; leurs stocks de contrats, dont les prestations n'ont pas &eacute;t&eacute;  demand&eacute;es &agrave; fin 2016. Elle observe un <strong>ph&eacute;nom&egrave;ne  d'accroissement des contrats non liquid&eacute;s &agrave; mesure que l'&acirc;ge de l'assur&eacute; augmente</strong> (alors que l'inverse devrait s'observer pour ce type de contrat dont les  prestations sont li&eacute;es &agrave; la cessation d'activit&eacute;)&nbsp;:</p><ul class="ul">
<li class="puce">10,6  milliards d'euros non r&eacute;clam&eacute;s apr&egrave;s 62 ans,</li>
<li class="puce">5,4  milliards d'euros non r&eacute;clam&eacute;s apr&egrave;s 65 ans,</li>
<li class="puce">1,8  milliard d'euros non r&eacute;clam&eacute;s apr&egrave;s 70 ans.</li></ul>
<br>
L'ACPR met l'accent sur les <strong>probl&eacute;matiques inh&eacute;rentes aux contrats  d'entreprise &agrave; adh&eacute;sion obligatoire</strong>. Ces derniers sont expos&eacute;s au ph&eacute;nom&egrave;ne  de d&eacute;sh&eacute;rence en raison de l'insuffisance d'information n&eacute;cessaire pour  identifier et localiser les b&eacute;n&eacute;ficiaires (mobilit&eacute; professionnelle,  disparition de l'entreprise, donn&eacute;es des bulletins d'adh&eacute;sion erron&eacute;es...). Les  organismes assureurs perdent davantage contact avec les b&eacute;n&eacute;ficiaires de ces  contrats (jusqu'&agrave; 90 % des assur&eacute;s de 70 ans pour lesquels l'adresse est  inconnue). Par ailleurs, l'assur&eacute; n'a pas toujours conscience que le contrat  souscrit, non par lui mais de fa&ccedil;on obligatoire par l'entreprise, fait na&icirc;tre  des droits individuels qui lui sont dus. 
<br>
<br>
<strong>Note</strong> : <em>L'Autorit&eacute; avait d&eacute;j&agrave;  mis en garde sur les difficult&eacute;s de ces contrats, dans son rapport du 28 avril  2016 sur les contrats en d&eacute;sh&eacute;rence relatif, cette fois, &agrave; l'assurance vie.  Selon elle, des travaux &eacute;taient n&eacute;cessaires pour am&eacute;liorer la qualit&eacute; des  donn&eacute;es contenues dans les bases clients. </em>
<br>
<br>
Les<strong> modalit&eacute;s de mise  en &oelig;uvre de l'obligation d'information</strong> n'ayant pas &eacute;t&eacute; pr&eacute;cis&eacute;es par la loi  Sapin, la majorit&eacute; des assureurs interrog&eacute;s a tenu ses engagements en apposant  une mention particuli&egrave;re dans le relev&eacute; de situation annuel ou par envoi d'un  courrier annuel sp&eacute;cifique. L'ACPR estime toutefois que la 1&egrave;re  solution n'est pas satisfaisante puisque l'assur&eacute; risque de ne pas saisir la  pertinence de l'information, celle-ci &eacute;tant noy&eacute;e parmi celles propres au  relev&eacute; de situation annuel.
<br>
<br>
Diverses actions, mises en avant par l'ACPR, pourraient &ecirc;tre  men&eacute;es afin de <strong>rem&eacute;dier &agrave; ce risque de  d&eacute;sh&eacute;rence</strong>&nbsp;:</p><ul class="ul">
<li class="puce">favoriser  la liquidation des contrats de faibles montants,</li>
<li class="puce">clarifier  le sort des contrats ne comportant pas de terme fixe en l'absence de preuve du  d&eacute;c&egrave;s de l'assur&eacute; (l'id&eacute;e &eacute;tant de transf&eacute;rer les sommes &agrave; la Caisse des d&eacute;p&ocirc;ts  et consignation), </li>
<li class="puce">donner  acc&egrave;s aux donn&eacute;es de la S&eacute;curit&eacute; sociale afin de fiabiliser les fichiers  clients des assureurs,</li>
<li class="puce">se  servir de GIP Info retraite comme mod&egrave;le ou r&eacute;f&eacute;rence en mati&egrave;re de  centralisation d'information.</li></ul>
<br>
<em><strong>Source</strong> : <a href="javascript:var w=window.open('https://acpr.banque-france.fr/sites/default/files/media/2018/05/28/20180524_rapportretraitesupp2018.pdf','','left=220, top=200, height=620, width=980,toolbar=0,location=0,directories=1,status=0,menubar=1,scrollbars=1,resizable=1,copyhistory=0' );" class="lien_intro_souligne_NONGRAS">ACPR, Contrats  d&rsquo;assurance vie dont les prestations sont li&eacute;es &agrave; la cessation d&rsquo;activit&eacute;  professionnelle, 24 mai 2018</a> </em><br><em> </em></p><p>&nbsp;</p>